
import jax 
import jax.numpy as jnp

from nambu_class import NambuTensor 
from system_state import SupercondctingState
import custom_optimizer as copt 
from jax import tree_util
import numpy as np
import matplotlib.pyplot as plt
from jax import core
import self_energy_class 

from matplotlib import pyplot as plt 
# CONTAINS ALL STATIC THINGS WHICH ARE NOT ITERATED OVER 

# have a self-consistency flag to indicate whether self-consistent equation has to be done! if dynamic then just compute new sigma, otherwise if g static compute self-consistently
#jax.config.update("jax_disable_jit", True)

# have last g as an argument to help self-consistency solver of course

# jit over the self-consistency solver as its involved and calling it can be slow
# then use jax forloop instead to do real-time-evolution

# this is basically GOD class, defines the rules of the system and the size

class EilenbergerEvolution:

    def __init__(self, grid_parameters, system_parameters, optimization_parameters = None, sigma_scatterings = None):

        # setting the grid parameters of the system

        #omega_sampling: int, theta_sampling: int, cutoff: float, fine_omega_sampling = None, fine_cutoff = None
        self.omega_size = grid_parameters['omega_sampling'] if grid_parameters['omega_sampling'] % 2 == 0 else grid_parameters['omega_sampling'] + 1
        self.theta_size = grid_parameters['theta_sampling']
        self.cutoff = grid_parameters['cutoff']
        self.eta = 2 * self.cutoff/self.omega_size

        if 'fine_omega_sampling' in grid_parameters.keys():
            self.fine_omega_size = grid_parameters['fine_omega_sampling'] if grid_parameters['fine_omega_sampling'] % 2 == 0 else grid_parameters['fine_omega_sampling'] + 1
            self.fine_cutoff = grid_parameters['fine_cutoff']
            self.eta = 2 * self.fine_cutoff/self.fine_omega_size
        else:
            self.fine_omega_size = None
            self.fine_cutoff = None

        omega_array = jnp.linspace(-self.cutoff, self.cutoff, self.omega_size)
        theta_array = jnp.linspace(0., 2. * jnp.pi, self.theta_size, endpoint=False)

        # if fine grid is specified generate it
        fine_omega_array = None    
        if self.fine_omega_size is not None and self.fine_cutoff is not None:
            fine_omega_array = jnp.linspace(-self.fine_cutoff, self.fine_cutoff, self.fine_omega_size)
        
            # concatenate the arrays and remove duplicates 
            omega_array = jnp.concatenate((omega_array, fine_omega_array))
            omega_array = jnp.unique(omega_array)

        # generate the meshgrid of the energy and angle arrays
        omega_grid, theta_grid = jnp.meshgrid(omega_array, theta_array, indexing = 'ij')
        
        grid_shape = omega_grid.shape
        self.w_grid = jax.lax.stop_gradient(omega_grid) 
        self.theta_grid = jax.lax.stop_gradient(theta_grid) 
        self.ones_grid = jax.lax.stop_gradient(jnp.ones(grid_shape))    
        self.w_arr = jax.lax.stop_gradient(omega_array) 
        self.theta_arr = jax.lax.stop_gradient(theta_array) # used to be self.theta
        self.grid_shape = jax.lax.stop_gradient(grid_shape) # used to be self.grid_shape 
    
        self.critical_temperature = system_parameters['critical_temperature']
        self.gap_symmetry = system_parameters['gap_symmetry']
        self.bcs_coupling = self._get_BCS_coupling()
        self.average_indices = jax.lax.stop_gradient(system_parameters['average_indices'])
        self.dh_grid = tuple([ self.grid_shape[i] if i+2 not in self.average_indices else 1 for i in range(len(self.grid_shape))])
        #self.dh_grid_shape = tuple([(self.grid_shape[i] if i in self.keep_indices else 1) for i in range(len(self.grid_shape))])

        self.optimization_parameters = optimization_parameters
        self.sigma_scatterings = sigma_scatterings
        sigmas, breakoffs = self._generate_sigma_objects()
        self.sigma_objects = sigmas
        self.break_off_indicies = jax.lax.stop_gradient(breakoffs)

    def _get_gap_symmetry_function(self):
        """A function generating the gap symmetry function given the symmetry type

        Args:
            gap_symmetry (str): description of the gap symmetry function: s, d-nodal or d-antinodal
            theta_grid (jnp.array): angle meshgrid generated by the get_computation_grid function

        Raises:
            ValueError: If the gap symmetry is not s, d-nodal or d-antinodal

        Returns:
            jnp.ndarray: The gap symmetry function defined over the angle meshgrid
        """
        if self.gap_symmetry == 's':
            return jnp.ones_like(self.theta_grid)
        elif gap_symmetry == 'd-nodal':
            return jnp.sqrt(2.)*jnp.sin(2.*self.theta_grid)
        elif gap_symmetry == 'd-antinodal':
            return jnp.sqrt(2.)*jnp.cos(2.*self.theta_grid)
        else:
            raise ValueError("Invalid gap symmetry")

    @staticmethod
    def get_bcs_gap_constant() -> float:
        """A function returning the value of the bcs gap constant

        Returns:
            float: BCS gap constant 
        """
        return 2.*jnp.exp(jnp.euler_gamma)/jnp.pi

    @staticmethod
    def get_bcs_ratio() -> float:
        """ A function returning the value of the ratio of Delta(0)/Tc in the BCS limit

        Returns:
            float: BCS ratio
        """
        return 2./EilenbergerEvolution.get_bcs_gap_constant()  

    def _get_BCS_coupling(self)->float:
        """A function returning the bcs coupling given the critical temperature

        Args:
            cutoff (float): high energy cutoff of the theory
            critical_temperature (float): critical temperature in the system

        Returns:
            float: Bcs coupling constant lambda
        """
        ### This is a useful function which gives the relation between BCS lambda and Tc for a fixed cutoff in the case of clean s-wave BCS equation 
        return 1./jnp.log(EilenbergerEvolution.get_bcs_gap_constant()*self.cutoff/self.critical_temperature) 

    def _generate_sigma_objects(self):
        break_off_indicies = [0]
        if self.sigma_scatterings is None:
            return None, break_off_indicies
        sigma_objects = []
        if 'Dynes' in self.sigma_scatterings:
            sigma_objects += [(self_energy_class.DynesScattering(scattering_rate= self.sigma_scatterings['Dynes'], theta_arr = self.theta_arr, omega_arr = self.w_arr))]
        
        if 'Elastic' in self.sigma_scatterings:
            sigma_objects += [(self_energy_class.ElasticScattering(scattering_rate= self.sigma_scatterings['Elastic'], theta_arr = self.theta_arr, omega_arr = self.w_arr))]

        for crt_object in sigma_objects:
            break_off_indicies += [2 * np.prod((crt_object._sigma_shape())) * len(crt_object._get_sigma_indicies()) + break_off_indicies[-1]]

        return sigma_objects, break_off_indicies

    def _integrate_over_omega(self,vals, axis):
        jitted_omega = jax.jit(copt.custom_jax_trapz, static_argnums = (2))
        return jitted_omega(y = vals, x = self.w_arr, axis = axis)

    def _integrate_over_theta(self,vals, axis):
        jitted_theta = jax.jit(copt.custom_jax_trapz, static_argnums = (2))
        return jitted_theta(y = vals, x = self.theta_arr, axis = axis)/jnp.pi/ 2

    def _integrate_over_axis(self,vals, axis):
        result = vals
        for index in axis:
            if index == -2:
                result = self._integrate_over_omega(vals = result, axis = index)
            elif index == -1:
                result = self._integrate_over_theta(vals = result, axis = index)
        return result

    def _delta_flatten(self, delta):
        return jnp.array([delta.real,delta.imag], dtype = jnp.float32)

    def _delta_unflatten(self, delta_arr):
        return delta_arr[0] + 1.j*delta_arr[1]

    def _hr2z(self, hr, indicies = None):
        return 1j*jnp.sqrt(hr._determinant())[0,0]

    def _get_z(self, Q:float, delta, sigma_rs = None, indices = None):
        h_r = self._Doppler_w_r(Q = Q) - (NambuTensor(1j *  jnp.real(delta) * self._get_gap_symmetry_function(), 2) +  NambuTensor(1j*jnp.imag(delta) * self._get_gap_symmetry_function(), 1)) 
        if sigma_rs is not None:
            for crt_sigma in sigma_rs:
                h_r = h_r.__sub__(crt_sigma, expansion_indices_right = (2,3))
            #sigma_r = jnp.sum(sigma_rs, axis = 0)
        return self._hr2z(h_r, indicies = indices)

    def _hr2gr(self, hr, indicies = None):
        return -1.j* hr/jnp.sqrt(hr._determinant()) 

    def _Doppler_w_r(self, Q:float,indices = None):
        return NambuTensor(self.w_grid - Q * jnp.cos(self.theta_grid) + 1.j * self.eta * self.ones_grid, 3)
        
    def _get_gr(self, Q:float, delta, sigma_rs = None, indices = None):
        #* Here sigma_rs is just a list of evaluated sigmas
        h_r = self._Doppler_w_r(Q = Q) - (NambuTensor(1j *  jnp.real(delta) * self._get_gap_symmetry_function(), 2) +  NambuTensor(1j*jnp.imag(delta) * self._get_gap_symmetry_function(), 1)) 
        if sigma_rs is not None:
            for crt_sigma in sigma_rs:
                h_r = h_r.__sub__(crt_sigma, expansion_indices_right = (2,3))
            #sigma_r = jnp.sum(sigma_rs, axis = 0)
        return  self._hr2gr(h_r)

    def _get_hr(self, Q:float, delta, sigma_rs = None, indices = None):
        #* Here sigma_rs is just a list of evaluated sigmas
        h_r = self._Doppler_w_r(Q = Q) - (NambuTensor(1j *  jnp.real(delta) * self._get_gap_symmetry_function(), 2) +  NambuTensor(1j*jnp.imag(delta) * self._get_gap_symmetry_function(), 1)) 
        if sigma_rs is not None:
            for crt_sigma in sigma_rs:
                h_r = h_r.__sub__(crt_sigma, expansion_indices_right = (2,3))
            #sigma_r = jnp.sum(sigma_rs, axis = 0)
        return h_r

    def _calc_gap(self, state_object):
        gk = state_object._f2gk()
        integrand = (gk * self._get_gap_symmetry_function())._trace('-') 
        return -0.25*self.bcs_coupling * (self._integrate_over_omega(self._integrate_over_theta(integrand,axis = 1),axis = 0)) 
      
    def _run_temperature_computation(self,Q,T):
        gr0 = None
        f_grid = self._thermal_occupation_numbers(temperature = T)
        f0 = NambuTensor(f_grid, 0)
        initial_guess_state = SupercondctingState(f0, gr0)
        self_cons_state = self._calc_self_consistent_gr(initial_state = initial_guess_state, Q = Q)
        return self_cons_state

    def _thermal_occupation_numbers(self, temperature: float) -> jnp.ndarray:
        return jnp.tanh(0.5*self.w_grid/temperature)

    def _calc_self_consistent_gr(self, initial_state,Q: float):
        #delta, sigmas = self._self_consistent_delta_sigma(initial_state, Q = Q)
        #state_f = initial_state.occupation 
        #return SupercondctingState(state_f,self._get_gr(Q = Q, delta = delta, sigma_rs = sigmas))
        h_r = self._self_consistent_hr(initial_state, Q = Q)
        gr = self._hr2gr(h_r)
        return SupercondctingState(initial_state.occupation,gr)

    def _self_consistent_hr(self, initial_state,Q: float):

        gr0 = initial_state.gr
        f = initial_state.occupation
        #TODO: Add a mechanism which recognizes over which axis we can average to reduce the dimensionality of the problem. It should be passed as an arguemnt to hr function 
        #TODO: Check the real-imaginary structure of the Jacobian A B B -A should be the structure! - not true, broken by the gap since gap does not come analytically
        # initial guess for the sigma and gap
        if gr0 is None:
            gap_0 = (1.0 + 0.0j) * 2
            hr0 = ((self._get_hr(Q= Q, delta = gap_0, sigma_rs = None) - self._Doppler_w_r(Q = Q)))._average(axis = self.average_indices)._flatten_nambu_object((1,2,3))
        else:
            gap_0 = self._calc_gap(initial_state) 
            if self.sigma_objects is not None:
                sigma_list = []
                for crt_object_index in range(jnp.shape(self.sigma_objects)[0]):
                    sigma_list += [self.sigma_objects[crt_object_index]._sigma_r(initial_state)._flatten_nambu_object(self.sigma_objects[crt_object_index]._get_sigma_indicies())]
            hr0 = (self._get_hr(Q= Q, delta = gap_0, sigma_rs = sigma_list) - self._Doppler_w_r(Q = Q))._average(axis = self.average_indices)._flatten_nambu_object((1,2,3))

        problem_solver = lambda dhr: self._self_consistent_dh(dh = dhr, Q = Q, f = f)
        
        #problem_solver_jacobian = lambda dhr: self._self_consistent_dh_jacobian(dhr, Q = Q, f = f)

        jitted_solver = jax.jit(problem_solver)
        #jitted_jacobian = jax.jit(problem_solver_jacobian)

        dh_final = copt._iterative_solver(jitted_solver, hr0, optimization_parameters = self.optimization_parameters)
        return NambuTensor._unflatten_nambu_object(dh_final, self.dh_grid, (1,2,3)) + self._Doppler_w_r(Q = Q)

    def _self_consistent_delta_sigma(self, initial_state,Q: float):

        gr0 = initial_state.gr
        f = initial_state.occupation

        new_state = initial_state

        delta_sigma_0 = jnp.zeros(self.break_off_indicies[-1] + 2)

        # initial guess for the sigma and gap
        if gr0 is None:
            gap_0 = 1.5 + 0.j
            delta_sigma_0 = delta_sigma_0.at[:2].set(self._delta_flatten(gap_0))
            gr0 = self._get_gr(Q= Q, delta = gap_0, sigma_rs = None)
            new_state = SupercondctingState(f,gr0)

        else:
            gap_0 = self._calc_gap(initial_state)
            delta_sigma_0 = delta_sigma_0.at[:2].set(self._delta_flatten(gap_0))
        # its a list of all the sigma values which are necessary 

        if self.sigma_objects is not None:
            for crt_object_index in range(jnp.shape(self.sigma_objects)[0]):
                delta_sigma_0 = delta_sigma_0.at[self.break_off_indicies[crt_object_index] +2:self.break_off_indicies[crt_object_index+1] + 2].set(self.sigma_objects[crt_object_index]._sigma_r(new_state)._flatten_nambu_object(self.sigma_objects[crt_object_index]._get_sigma_indicies()))

        problem_solver = lambda delta_sigma_list: self._sigma_delta_solver(delta_sigma_list,f,Q)

        jitted_solver = jax.jit(problem_solver)
        delta_sigma_final = copt._iterative_solver(jitted_solver, delta_sigma_0, optimization_parameters = self.optimization_parameters)
        delta_final = delta_sigma_final[:2]

        if self.sigma_objects is None:
            sigma_final = None
            return self._delta_unflatten(delta_final), None
        else:
            sigma_final = delta_sigma_final[2:]
            sigma_list = []
            for ind in range(len(self.break_off_indicies) -1):
                crt_flat_sigma = sigma_final[self.break_off_indicies[ind]:self.break_off_indicies[ind+1]]
                sigma_list += [self.sigma_objects[ind]._unflatten_nambu_object(crt_flat_sigma,self.sigma_objects[ind].sigma_shape, included_indices = self.sigma_objects[ind]._get_sigma_indicies())]

            return self._delta_unflatten(delta_final), sigma_list

    def _self_consistent_dh(self, dh,Q:float,f):
        
        h_total = self._Doppler_w_r(Q) + NambuTensor._unflatten_nambu_object(dh, self.dh_grid, included_indices = (1,2,3))
        
        crt_state = SupercondctingState(f,self._hr2gr(h_total))
            
        delta_value =  self._calc_gap(state_object = crt_state)
        sigma_values = []
        if self.sigma_objects is not None:
            for crt_obj_index in range(jnp.shape(self.sigma_objects)[0]):
                sigma_values += [self.sigma_objects[crt_obj_index]._sigma_r(system_state = crt_state)]
    
        return (h_total - self._get_hr(Q = Q, delta = delta_value, sigma_rs = sigma_values))._average(axis = self.average_indices)._flatten_nambu_object((1,2,3))

    def _dg_dsigma(self,hr):
        crt_g = self._hr2gr(hr)
        crt_z = self._hr2z(hr)
        g_flat = (crt_g/jnp.sqrt(crt_z))._flatten_nambu_object((1,2,3))
        g_flat_new = g_flat[: jnp.size(g_flat)//2] + 1j * g_flat[jnp.size(g_flat)//2:]
        data_reshape_size = tuple(self.grid_shape) + (3,)
        new_data = jnp.reshape(g_flat_new,data_reshape_size)
        axes = (new_data.ndim-1,) + tuple(range(0, new_data.ndim-1))
        new_data = jnp.transpose(new_data,axes = axes) 
        return (-jnp.einsum('ijk, mjk -> imjk', new_data, new_data) + jnp.tensordot(jnp.identity(3), 1/crt_z, axes = 0)) 


    def _ddelta_dg(self, state_object, Q:float):

        out_data = jnp.zeros((3,3) + self.grid_shape) + 0j
        
        for m in range(0,3):
            traces_1_m = (NambuTensor(jnp.ones(self.grid_shape), m + 1) @ ( state_object.occupation))._trace('-')
            traces_2_m = (NambuTensor(jnp.ones(self.grid_shape), 3) @ NambuTensor(jnp.ones(self.grid_shape), m + 1) @ NambuTensor(jnp.ones(self.grid_shape), 3) @ (state_object.occupation)._conj()._transpose())._trace('+')
            sigma_nambu = 2 * (-1)**(m+1) * (- 1j* NambuTensor(traces_1_m, '-') +  1j* NambuTensor( traces_2_m, '+'))._flatten_nambu_object(included_indices = (1,2,3))
            sigma_nambu = 1j * sigma_nambu[jnp.size(sigma_nambu)//2:]
            data_reshape_size = tuple(self.grid_shape) + (3,)
            sigma_nambu = jnp.reshape(sigma_nambu,data_reshape_size)
            axes = (sigma_nambu.ndim-1,) + tuple(range(0, sigma_nambu.ndim-1))
            sigma_nambu = jnp.transpose(sigma_nambu,axes = axes) 
            out_data = out_data.at[:,m].set(sigma_nambu)

        return out_data * -0.25*self.bcs_coupling/ 2 / jnp.pi * (self.w_arr[1] - self.w_arr[0]) * (self.theta_arr[1] - self.theta_arr[0]) 

    def _self_consistent_dh_jacobian(self, dh,Q:float,f):
        h_total = self._Doppler_w_r(Q) + NambuTensor._unflatten_nambu_object(dh, self.dh_grid, included_indices = (1,2,3))
        
        crt_state = SupercondctingState(f,self._hr2gr(h_total))

        delta_derivative = self._ddelta_dg(state_object = crt_state, Q = Q)
        dgdh = self._dg_dsigma(hr = h_total)

        # Block checking ddelta/dg
        #print(self._delta_flatten(delta_derivative[1].transpose(1,2,0).flatten()).flatten())
        #my_func = lambda gr: self._calc_gap(state_object = SupercondctingState(f,NambuTensor._unflatten_nambu_object(gr,data_shape= self.grid_shape, included_indices = (1,2,3)))).real
        #derivative = jax.jacobian(my_func)(crt_state.gr._flatten_nambu_object((1,2,3)))
        #print(self._delta_flatten(delta_derivative[1].transpose(1,2,0).flatten()).flatten())
        #print(derivative)
        #print(jnp.max(jnp.abs(derivative - self._delta_flatten(delta_derivative[1].transpose(1,2,0).flatten()).flatten())))
        # assert False

        delta_complex_result = jnp.einsum('ikep, kjep -> ijep', delta_derivative, dgdh) * 1j
        delta_complex_result = jnp.einsum('ijep, fr -> friepj', delta_complex_result, jnp.ones(self.grid_shape))

        delta_complex_result = jnp.reshape(delta_complex_result, (3 * np.prod(self.grid_shape), 3 * np.prod(self.grid_shape)))
        #! Get rid of this, this no work 
        matrix_out = jnp.zeros((6 * np.prod(self.grid_shape), 6 * np.prod(self.grid_shape)), dtype = jnp.float32) 

        matrix_out = matrix_out.at[: 3 * np.prod(self.grid_shape), : 3 * np.prod(self.grid_shape)].set(delta_complex_result.real * 0)
        matrix_out = matrix_out.at[3 * np.prod(self.grid_shape):, 3 * np.prod(self.grid_shape):].set(delta_complex_result.real)
        matrix_out = matrix_out.at[: 3 * np.prod(self.grid_shape), 3 * np.prod(self.grid_shape):].set(delta_complex_result.real * 0)
        matrix_out = matrix_out.at[3 * np.prod(self.grid_shape):, : 3 * np.prod(self.grid_shape)].set(delta_complex_result.imag) 

        return jnp.identity(6 * np.prod(self.grid_shape)) - matrix_out

    def _sigma_delta_solver(self,delta_sigma_list,f,Q):
        result = jnp.zeros(delta_sigma_list.size)
        sigma_list = None

        if self.sigma_objects is not None:
            sigma_list = []
            #? Maybe this can be further optimized
            for ind in range(jnp.shape(self.sigma_objects)[0]):
                sigma_list.append(self.sigma_objects[ind]._unflatten_sigma(delta_sigma_list[2:][self.break_off_indicies[ind]:self.break_off_indicies[ind+1]]))


        jitted_delta = jax.jit(self._delta_condition, static_argnums = (1,))
        result = result.at[:2].set(jitted_delta(Q = Q, f = f, sigmas = sigma_list, delta = self._delta_unflatten(delta_sigma_list[:2])))
        jitted_sigma = jax.jit(self._sigma_condition, static_argnums = (1,))

        if sigma_list is not None:
            result = result.at[2:].set(jitted_sigma(Q = Q, f = f,sigmas = sigma_list,delta = self._delta_unflatten(delta_sigma_list[:2])))
        
        return result#, sigma_self_cons
    
    def _delta_condition(self, Q:float, f:jnp.ndarray,sigmas:jnp.ndarray,delta):
        return self._delta_flatten(delta - self._calc_gap(state_object = SupercondctingState(f,self._get_gr(Q = Q, delta = delta, sigma_rs = sigmas))))

    def _sigma_condition(self, Q:float, f:jnp.ndarray,sigmas:jnp.ndarray,delta):
        crt_state = SupercondctingState(f,self._get_gr(Q = Q, delta = delta, sigma_rs = sigmas))
        output = jnp.zeros(self.break_off_indicies[-1])
        for crt_obj_index in range(jnp.shape(self.sigma_objects)[0]):
            output = output.at[self.break_off_indicies[crt_obj_index]:self.break_off_indicies[crt_obj_index+1]].set(self.sigma_objects[crt_obj_index]._self_consistency(sigma = sigmas[crt_obj_index],system_state = crt_state)._flatten_nambu_object(self.sigma_objects[crt_obj_index]._get_sigma_indicies()))
        return output


    def _delta_sigma_jacobian(self,delta_sigma_list,f,Q):

        delta = self._delta_unflatten(delta_sigma_list[:2])
        sigma_list = None

        if self.sigma_objects is not None:
            sigma_list = []
            for ind in range(jnp.shape(self.sigma_objects)[0]):
                sigma_list.append(self.sigma_objects[ind]._unflatten_sigma(delta_sigma_list[2:][self.break_off_indicies[ind]:self.break_off_indicies[ind+1]]))
        

        g_obj = self._get_gr(Q = Q, delta = delta, sigma_rs = sigma_list)
        state_object = SupercondctingState(f,g_obj)
        crt_Z = self._get_z(Q = Q, delta = delta, sigma_rs = sigma_list)
        
        #! something very weird is going on we can access array elements that do not exist
        #* return a delta matrix of shape (2,6,1000,20)
        delta_matrix = self._delta_condition_dg(state_object, crt_Z)
        #* Perform epsilon and theta average
        delta_matrix_average = self._integrate_over_axis(delta_matrix, axis = (-2,-1))

        #* construct the answer matrix 
        out_matrix = jnp.zeros((2 + self.break_off_indicies[-1],2 + self.break_off_indicies[-1]))
        out_matrix = out_matrix.at[:2,0].set( delta_matrix_average[:2,3]) # t2 imaginary part, labeling starts from 0 
        out_matrix = out_matrix.at[:2,1].set( delta_matrix_average[:2,1]) # t1 imaginary, labeling starts from 0 

        #TODO: optimize the diagonal matrix entires
        #* append all the delta rows 
        if self.sigma_objects is not None:
            #* Compute indicies over which things should be averaged
            average_indicies = []
            for sigma_obj in self.sigma_objects:
                shape_of_object = sigma_obj._sigma_shape()
                average_indicies += [jnp.where(jnp.array(shape_of_object) == 1)[0] - 2] # subtract 2 to get -1 and -2 indicies #TODO check if this works

            #* Compute individual sigma jacobians 
            sigma_matrices_jacobian = []
            for sigma_obj in self.sigma_objects:
                sigma_matrices_jacobian.append(sigma_obj._sigma_jacobian(state_object, crt_Z))

            for crt_index in range(jnp.shape(self.sigma_objects)[0]):
                if average_indicies[crt_index].size < 1:
                    crt_delta_average = delta_matrix
                else:
                    crt_delta_average = self._integrate_over_axis(delta_matrix, axis = average_indicies[crt_index])
                
                crt_included_indicies = jnp.sort(jnp.append(jnp.array(self.sigma_objects[crt_index]._get_sigma_indicies()) * 2, jnp.array(self.sigma_objects[crt_index]._get_sigma_indicies()) * 2 +1)) - 2

                crt_data = (crt_delta_average[:,crt_included_indicies]).flatten()
                #! Reshape is probably wrong again 
                out_matrix = out_matrix.at[:2,2 + self.break_off_indicies[crt_index]: 2 + self.break_off_indicies[crt_index+1]].set(crt_data.reshape(2, -self.break_off_indicies[crt_index] + self.break_off_indicies[crt_index+1]))

            #* append all delta columns 
            for crt_index in range(jnp.shape(self.sigma_objects)[0]):
                out_matrix = out_matrix.at[2 + self.break_off_indicies[crt_index]:2 + self.break_off_indicies[crt_index+1],0].set(self._integrate_over_axis(sigma_matrices_jacobian[crt_index], axis = (-2,-1))[...,3].flatten())
                out_matrix = out_matrix.at[2 + self.break_off_indicies[crt_index]:2 + self.break_off_indicies[crt_index+1],1].set(self._integrate_over_axis(sigma_matrices_jacobian[crt_index], axis = (-2,-1))[...,1].flatten())

            #* append all sigma rows and columns
            for crt_index_1 in range(jnp.shape(self.sigma_objects)[0]):
                for crt_index_2 in range(jnp.shape(self.sigma_objects)[0]):
                    crt_included_indicies = jnp.sort(jnp.append(jnp.array(self.sigma_objects[crt_index_2]._get_sigma_indicies()) * 2, jnp.array(self.sigma_objects[crt_index_2]._get_sigma_indicies()) * 2 +1)) - 2
                    crt_data = self._integrate_over_axis(sigma_matrices_jacobian[crt_index_1][...,crt_included_indicies,:,:],axis = average_indicies[crt_index_2]).flatten()
                    #! Check re-shaping
                    out_matrix.at[2+ self.break_off_indicies[crt_index_1]:2 + self.break_off_indicies[crt_index_1+1],2 + self.break_off_indicies[crt_index_2]: 2 + self.break_off_indicies[crt_index_2+1]].set(crt_data.reshape( -self.break_off_indicies[crt_index_1] +self.break_off_indicies[crt_index_1+1],-self.break_off_indicies[crt_index_2] +self.break_off_indicies[crt_index_2+1]))
        
        return jnp.identity(2 + self.break_off_indicies[-1]) - out_matrix
            
