"""
Analysis and plotting tools for postprocessed Keldysh data.

Loads and visualizes data generated by run_postprocessor.py
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import pickle

from demler_tools.file_manager import io, path_management
from demler_tools.data_analysis.image_file_tools import extended_savefig

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Matplotlib configuration for all plots - use LaTeX article style fonts
plt.rcParams['text.usetex'] = True
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Computer Modern Roman']
plt.rcParams['text.latex.preamble'] = r'\usepackage{amsmath} \usepackage{amssymb}'
plt.rcParams['font.size'] = 20


def load_postprocessed_data(timestamp, directory_job_index=0, running_machine='laptop'):
    """
    Load postprocessed data from timestamp folder.

    Args:
        timestamp: Timestamp folder identifier
        directory_job_index: Index of postprocessed result file to load (default 0)
        running_machine: 'laptop' or 'cluster_euler'

    Returns:
        dict: Postprocessed data dictionary with keys from run_postprocessor.py output
    """
    if not hasattr(path_management, 'project_data'):
        path_management.initialize(project_name='psBQP-keldysh')

    simulation_data_path = path_management.default_simulation_data_path(running_machine=running_machine)
    result_file = os.path.join(simulation_data_path, str(timestamp),
                               path_management.relative_path_raw_result_file().format(directory_job_index))

    # Check archive path if not found in simulation data path
    if not os.path.exists(result_file):
        archive_path = path_management.default_autoarchive_path(running_machine=running_machine)
        result_file = os.path.join(archive_path, str(timestamp),
                                   path_management.relative_path_raw_result_file().format(directory_job_index))

    if not os.path.exists(result_file):
        raise FileNotFoundError(f"Postprocessed data file not found for timestamp {timestamp}, job {directory_job_index}")

    with open(result_file, 'rb') as f:
        data = pickle.load(f)

    return data


def plot_transmitivity_results(timestamp, directory_job_index=0, job_indices=None, plot_pulses=False,
                               save_plot=False, save_dir=None, running_machine='laptop', colormap='Blues',
                               xlim_pulses=None):
    """
    Plot transmitivity analysis from postprocessed data.

    Creates a 2-panel transmitivity plot and optionally a 2x2 time trace plot.

    Args:
        timestamp: Postprocessed timestamp folder
        directory_job_index: Index or list of indices of postprocessed result files to load (default 0)
        job_indices: Deprecated parameter (kept for backward compatibility, not used)
        plot_pulses: If False, no pulse plots. If True, plots all jobs. If list, plots only specified job indices.
        save_plot: Whether to save plots (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: Machine type for data loading ('laptop' or 'cluster_euler')
        colormap: Colormap name for line colors (default 'Blues')
        xlim_pulses: Tuple (xmin, xmax) for x-axis limits on pulse plots (default None = auto)

    Returns:
        dict or list: Loaded postprocessed data (dict if single index, list if multiple)
    """
    # Normalize directory_job_index to list
    if isinstance(directory_job_index, int):
        directory_job_indices = [directory_job_index]
    else:
        directory_job_indices = directory_job_index

    # Create transmitivity plots (2 panels)
    fig_trans, axes = plt.subplots(1, 2, figsize=(12, 5))
    ax_trans, ax_jmax = axes

    # Color cycle for different directory job indices using continuous colormap
    cmap = plt.get_cmap(colormap)
    colors = cmap(np.linspace(0.3, 0.9, len(directory_job_indices)))

    # Store loaded data
    loaded_data_list = []

    # Plot each directory job index
    for idx, dir_job_idx in enumerate(directory_job_indices):
        color = colors[idx]

        # Load postprocessed data
        data = load_postprocessed_data(timestamp, dir_job_idx, running_machine)
        loaded_data_list.append(data)

        # Extract data arrays
        I_in_max_array = data['incoming_current_amplitudes']
        J_max_array = data['transmitted_current_amplitudes']
        transmitivity_array = data['transmitivity']

        # Extract parameters from first job for legend
        system_params = data['system_parameters'][0]
        field_params = data.get('field_params', [{}])[0]

        temperature = system_params.get('temperature', None)
        eta = system_params.get('eta', None)
        fwhm = field_params.get('FWHM', None)

        # Build legend label with available parameters (using LaTeX formatting)
        label_parts = []
        if temperature is not None:
            label_parts.append(r'$T/T_c=' + str(np.round(temperature, 3)) + r'$')
        if eta is not None:
            label_parts.append(r'$ \eta/T_c=' + str(np.round(eta, 3)) + r'$')
        if fwhm is not None:
            label_parts.append(r'$\mathrm{FWHM}\cdot T_c=' + str(np.round(fwhm, 3)) + r'$')
        legend_label = ', '.join(label_parts)

        # Panel a: Transmitivity vs I_in_max
        ax_trans.plot(I_in_max_array, transmitivity_array, '-',
                     color=color, linewidth=3, label=legend_label, alpha=0.8)

        # Panel b: Transmitivity vs I_T_max
        ax_jmax.plot(J_max_array, transmitivity_array, '-',
                    color=color, linewidth=3, label=legend_label, alpha=0.8)

    # Configure panel a
    ax_trans.set_xlabel(r'$I_{in,\mathrm{max}}$', fontsize=21)
    ax_trans.set_ylabel(r'$T\,(I_{T,\mathrm{max}}/I_{in,\mathrm{max}})$', fontsize=21)
    ax_trans.set_title(r'Transmitivity vs Input Current', fontsize=23)
    ax_trans.legend(fontsize=12)

    # Configure panel b
    ax_jmax.set_xlabel(r'$I_{T,\mathrm{max}}$', fontsize=21)
    ax_jmax.set_ylabel(r'$T\,(I_{T,\mathrm{max}}/I_{in,\mathrm{max}})$', fontsize=21)
    ax_jmax.set_title(r'Transmitivity vs Transmitted Current', fontsize=23)
    ax_jmax.legend(fontsize=12)

    fig_trans.tight_layout()

    # Set up save directory if needed
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

    if save_plot:
        # Format job indices for filename
        jobs_str = '_'.join(map(str, directory_job_indices))
        save_path = os.path.join(save_dir, f'transmitivity_analysis_{timestamp}_jobs{jobs_str}.svg')
        extended_savefig(fig_trans, save_path, timestamp)

    # Create pulse traces plot if requested (one plot per directory job index)
    if plot_pulses is not False and plot_pulses is not None:
        for dir_idx, data in enumerate(loaded_data_list):
            dir_job_idx = directory_job_indices[dir_idx]

            # Extract time series data
            gap_evolution = data['gap_evolution']
            current_evolution = data['current_evolution']
            vector_potential_evolution = data['vector_potential_evolution']
            incoming_current_pulses = data['incoming_current_pulses']
            times = data['times']

            # Determine which jobs to plot
            if isinstance(plot_pulses, list):
                plot_job_indices = plot_pulses
            elif plot_pulses is True:
                plot_job_indices = range(len(gap_evolution))
            else:
                plot_job_indices = range(len(gap_evolution))

            # Create 2x2 plot
            fig_pulses, axes = plt.subplots(2, 2, figsize=(14, 10))
            ax_input, ax_vpot = axes[0]
            ax_gap, ax_current = axes[1]

            # Color cycle for different jobs using continuous colormap
            cmap = plt.get_cmap(colormap)
            colors_jobs = cmap(np.linspace(0.3, 0.9, len(plot_job_indices)))

            # Get critical current and temperature for labels/normalization
            system_params = data['system_parameters'][0]
            I_c = system_params.get('critical_current', 1.0)
            T_c = system_params.get('critical_temperature', 1.0)

            for idx, job_idx in enumerate(plot_job_indices):
                color = colors_jobs[idx]

                # Extract data for this job
                times_job = times[job_idx]
                gaps_job = np.abs(gap_evolution[job_idx])
                current_job = current_evolution[job_idx]
                vpot_job = vector_potential_evolution[job_idx]
                input_job = incoming_current_pulses[job_idx]

                # Normalize time by T_c
                times_norm = times_job * T_c

                # Compute max incoming current for label
                I_in_max = np.max(np.abs(input_job))
                label = r'$I_{in}/I_c=' + str(np.round(I_in_max/I_c, 3)) + r'$'

                # Plot gap vs time (no label)
                ax_gap.plot(times_norm, gaps_job, '-', color=color, linewidth=3, alpha=0.8)

                # Plot vector potential vs time (no label)
                ax_vpot.plot(times_norm, vpot_job, '-', color=color, linewidth=3, alpha=0.8)

                # Plot current vs time (no label)
                ax_current.plot(times_norm, current_job, '-', color=color, linewidth=3, alpha=0.8)

                # Plot incoming current vs time (with label)
                ax_input.plot(times_norm, input_job, '-', color=color, linewidth=3, label=label, alpha=0.8)

            # Configure gap plot
            ax_gap.set_xlabel(r'$t \cdot T_c$', fontsize=21)
            ax_gap.set_ylabel(r'$|\Delta(t)|$', fontsize=21)
            ax_gap.set_title(r'Gap Evolution', fontsize=23)
            if xlim_pulses is not None:
                ax_gap.set_xlim(xlim_pulses)

            # Configure vector potential plot
            ax_vpot.set_xlabel(r'$t \cdot T_c$', fontsize=21)
            ax_vpot.set_ylabel(r'$A(t)$', fontsize=21)
            ax_vpot.set_title(r'Vector Potential', fontsize=23)
            if xlim_pulses is not None:
                ax_vpot.set_xlim(xlim_pulses)

            # Configure current plot
            ax_current.set_xlabel(r'$t \cdot T_c$', fontsize=21)
            ax_current.set_ylabel(r'$I_{T}(t)$', fontsize=21)
            ax_current.set_title(r'Transmitted Current', fontsize=23)
            if xlim_pulses is not None:
                ax_current.set_xlim(xlim_pulses)

            # Configure incoming current plot
            ax_input.set_xlabel(r'$t \cdot T_c$', fontsize=21)
            ax_input.set_ylabel(r'$I_{in}(t)$', fontsize=21)
            ax_input.set_title(r'Incoming Current Pulse', fontsize=23)
            ax_input.legend(fontsize=13)
            if xlim_pulses is not None:
                ax_input.set_xlim(xlim_pulses)

            # Add overall title if multiple directory jobs
            if len(directory_job_indices) > 1:
                fig_pulses.suptitle(f'Directory Job {dir_job_idx}', fontsize=23, y=0.995)

            fig_pulses.tight_layout()

            if save_plot:
                # Format plotted job indices for filename
                pulse_jobs_str = '_'.join(map(str, plot_job_indices))
                save_path = os.path.join(save_dir, f'pulse_traces_{timestamp}_pulses_{pulse_jobs_str}_dirjob{dir_job_idx}.svg')
                extended_savefig(fig_pulses, save_path, timestamp)

    plt.show()

    # Return single dict if single index, list if multiple
    if len(loaded_data_list) == 1:
        return loaded_data_list[0]
    else:
        return loaded_data_list


def plot_spectral_signatures(timestamp, directory_job_index=0, plot_jobs=None,
                             save_plot=False, save_dir=None, running_machine='laptop', colormap='Blues',
                             xlim=None, ylim=None, plot_FT=False):
    """
    Plot spectral analysis from postprocessed data.

    Creates a 3x3 plot (if FFT data available or plot_FT=True) showing time and frequency domains,
    or a 1x3 plot (if only time data available and plot_FT=False) showing time domain only.

    Args:
        timestamp: Postprocessed timestamp folder
        directory_job_index: Index or list of indices of postprocessed result files to load (default 0)
        plot_jobs: List of job indices to plot. If None, plots all jobs. If list, plots only specified.
        save_plot: Whether to save plots (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: Machine type for data loading ('laptop' or 'cluster_euler')
        colormap: Colormap name for line colors (default 'Blues')
        xlim: Tuple (xmin, xmax) for x-axis limits on frequency domain plots (default None = auto)
        ylim: Tuple (ymin, ymax) for y-axis limits on all plots (default None = auto)
        plot_FT: If True, compute FFT on the fly even if not pre-computed (default False)

    Returns:
        dict or list: Loaded postprocessed data (dict if single index, list if multiple)
    """
    # Normalize directory_job_index to list
    if isinstance(directory_job_index, int):
        directory_job_indices = [directory_job_index]
    else:
        directory_job_indices = directory_job_index

    # Set up save directory if needed
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

    # Store loaded data
    loaded_data_list = []

    # Process each directory job index
    for dir_idx, dir_job_idx in enumerate(directory_job_indices):
        # Load postprocessed data
        data = load_postprocessed_data(timestamp, dir_job_idx, running_machine)
        loaded_data_list.append(data)

        # Extract time series data
        gap_evolution = data['gap_evolution']
        current_evolution = data['current_evolution']
        vector_potential_evolution = data['vector_potential_evolution']
        times = data['times']

        # Check if FFT data available
        has_fft = 'gap_fft' in data

        # Determine which jobs to plot
        if plot_jobs is None:
            plot_job_indices = range(len(gap_evolution))
        else:
            plot_job_indices = plot_jobs

        # Get T_c for normalization
        T_c = data['system_parameters'][0]['critical_temperature']

        # Compute FFT on the fly if requested
        if plot_FT:
            gap_fft = []
            current_fft = []
            vpot_fft = []
            omega = []

            for job_idx in range(len(gap_evolution)):
                times_job = times[job_idx]
                gaps_job = gap_evolution[job_idx]
                currents_job = current_evolution[job_idx]
                vector_potentials_job = vector_potential_evolution[job_idx]

                # Compute FFT following run_postprocessor.py conventions
                dt = times_job[1] - times_job[0]
                N_t = len(times_job)

                # Frequency grid construction
                freq = np.fft.fftfreq(N_t, d=dt)
                omega_job = 2 * np.pi * freq
                omega_shifted = np.fft.fftshift(omega_job)
                omega.append(omega_shifted)

                # Phase correction (center pulse at t=0)
                t_center_idx = np.argmax(np.abs(vector_potentials_job))
                t_center = times_job[t_center_idx]
                phase_correction = np.exp(-1j * omega_job * t_center)

                # Gap FFT (operates on gap deviation - DC removal)
                gap_abs = np.abs(gaps_job)
                gap_deviation = gap_abs - gap_abs[0]
                gap_fft_raw = np.fft.fft(gap_deviation) * dt
                gap_fft_corrected = gap_fft_raw * phase_correction
                gap_fft_shifted = np.fft.fftshift(gap_fft_corrected)
                gap_fft.append(gap_fft_shifted)

                # Current FFT (use full time series - no DC removal)
                current_fft_raw = np.fft.fft(np.real(currents_job)) * dt
                current_fft_corrected = current_fft_raw * phase_correction
                current_fft_shifted = np.fft.fftshift(current_fft_corrected)
                current_fft.append(current_fft_shifted)

                # Vector potential FFT (use full time series)
                A_fft_raw = np.fft.fft(vector_potentials_job) * dt
                A_fft_corrected = A_fft_raw * phase_correction
                A_fft_shifted = np.fft.fftshift(A_fft_corrected)
                vpot_fft.append(A_fft_shifted)

            # Mark as having FFT data
            has_fft = True
        elif has_fft:
            # Extract pre-computed FFT data
            gap_fft = data['gap_fft']
            current_fft = data['current_fft']
            vpot_fft = data['vpot_fft']
            omega = data['omega']

        if has_fft:

            # Extract incoming current pulses for labeling
            incoming_current_pulses = data.get('incoming_current_pulses', None)
            field_params = data.get('field_params', [{}])

            # Create 3x3 plot
            fig, axes = plt.subplots(3, 3, figsize=(18, 14))

            # Color cycle for different jobs using continuous colormap
            cmap = plt.get_cmap(colormap)
            colors_jobs = cmap(np.linspace(0.3, 0.9, len(plot_job_indices)))

            for idx, job_idx in enumerate(plot_job_indices):
                color = colors_jobs[idx]

                # Create label from amplitude and FWHM
                label_parts = []
                try:
                    if incoming_current_pulses is not None and job_idx < len(incoming_current_pulses):
                        I_in_max = np.max(np.abs(incoming_current_pulses[job_idx]))
                        label_parts.append(r'I_{\mathrm{max}}=' + str(np.round(I_in_max, 2)))

                    if field_params is not None and job_idx < len(field_params):
                        fwhm = field_params[job_idx].get('FWHM', None)
                        if fwhm is not None:
                            label_parts.append(r'FWHM \cdot T_c=' + str(np.round(fwhm, 2)))

                    if label_parts:
                        label = '$' + ', '.join(label_parts) + '$'
                    else:
                        label = str(job_idx)
                except (IndexError, KeyError, TypeError):
                    label = str(job_idx)

                # Extract data for this job
                times_job = times[job_idx]
                gaps_job = np.abs(gap_evolution[job_idx])
                current_job = current_evolution[job_idx]
                vpot_job = vector_potential_evolution[job_idx]

                # Normalize time by T_c
                times_norm = times_job * T_c

                # FFT data for this job
                gap_fft_job = gap_fft[job_idx]
                current_fft_job = current_fft[job_idx]
                vpot_fft_job = vpot_fft[job_idx]
                omega_job = omega[job_idx]

                # Normalize omega by T_c
                omega_norm = omega_job / T_c

                # Row 0: Vector Potential
                axes[0, 0].plot(times_norm, vpot_job, '-', color=color, linewidth=2, label=label, alpha=0.8)
                axes[0, 1].plot(omega_norm, np.real(vpot_fft_job), '-', color=color, linewidth=2, label=label, alpha=0.8)
                axes[0, 2].plot(omega_norm, np.imag(vpot_fft_job), '-', color=color, linewidth=2, label=label, alpha=0.8)

                # Row 1: Gap (no labels)
                axes[1, 0].plot(times_norm, gaps_job / T_c, '-', color=color, linewidth=2, alpha=0.8)
                axes[1, 1].plot(omega_norm, np.real(gap_fft_job) / T_c, '-', color=color, linewidth=2, alpha=0.8)
                axes[1, 2].plot(omega_norm, np.imag(gap_fft_job) / T_c, '-', color=color, linewidth=2, alpha=0.8)

                # Row 2: Current (no labels)
                axes[2, 0].plot(times_norm, current_job, '-', color=color, linewidth=2, alpha=0.8)
                axes[2, 1].plot(omega_norm, np.real(current_fft_job), '-', color=color, linewidth=2, alpha=0.8)
                axes[2, 2].plot(omega_norm, np.imag(current_fft_job), '-', color=color, linewidth=2, alpha=0.8)

            # Get gap at t=0 from first plotted job for reference lines
            first_job_idx = plot_job_indices[0]
            gap_t0 = np.abs(gap_evolution[first_job_idx][0]) / T_c

            # Determine xlim for frequency plots
            freq_xlim = xlim if xlim is not None else (-10, 10)

            # Configure axes - Row 0 (Vector Potential)
            axes[0, 0].set_xlabel(r'$t \cdot T_c$', fontsize=21)
            axes[0, 0].set_ylabel(r'$A(t)$', fontsize=21)
            axes[0, 0].set_title(r'Vector Potential', fontsize=23)
            axes[0, 0].legend(fontsize=13)
            if ylim is not None:
                axes[0, 0].set_ylim(ylim)

            axes[0, 1].set_xlabel(r'$\omega/T_c$', fontsize=21)
            axes[0, 1].set_ylabel(r'$Re[A(\omega)]$', fontsize=21)
            axes[0, 1].set_title(r'Real', fontsize=23)
            axes[0, 1].set_xlim(freq_xlim)
            if ylim is not None:
                axes[0, 1].set_ylim(ylim)
            # Add reference lines for ±Δ and ±2Δ
            for delta_val, label_text in [(gap_t0, r'$\Delta$'), (2*gap_t0, r'$2\Delta$')]:
                axes[0, 1].axvline(delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[0, 1].axvline(-delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[0, 1].text(delta_val + 0.3, 0.95, label_text, transform=axes[0, 1].get_xaxis_transform(),
                               ha='left', va='top', fontsize=18, color='gray')

            axes[0, 2].set_xlabel(r'$\omega/T_c$', fontsize=21)
            axes[0, 2].set_ylabel(r'$Im[A(\omega)]$', fontsize=21)
            axes[0, 2].set_title(r'Imaginary', fontsize=23)
            axes[0, 2].set_xlim(freq_xlim)
            if ylim is not None:
                axes[0, 2].set_ylim(ylim)
            # Add reference lines for ±Δ and ±2Δ
            for delta_val, label_text in [(gap_t0, r'$\Delta$'), (2*gap_t0, r'$2\Delta$')]:
                axes[0, 2].axvline(delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[0, 2].axvline(-delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[0, 2].text(delta_val + 0.3, 0.95, label_text, transform=axes[0, 2].get_xaxis_transform(),
                               ha='left', va='top', fontsize=18, color='gray')

            # Configure axes - Row 1 (Gap)
            axes[1, 0].set_xlabel(r'$t \cdot T_c$', fontsize=21)
            axes[1, 0].set_ylabel(r'$|\Delta(t)|/T_c$', fontsize=21)
            axes[1, 0].set_title(r'Gap', fontsize=23)
            if ylim is not None:
                axes[1, 0].set_ylim(ylim)

            axes[1, 1].set_xlabel(r'$\omega/T_c$', fontsize=21)
            axes[1, 1].set_ylabel(r'$Re[\Delta(\omega)]/T_c$', fontsize=21)
            axes[1, 1].set_title(r'Real', fontsize=23)
            axes[1, 1].set_xlim(freq_xlim)
            if ylim is not None:
                axes[1, 1].set_ylim(ylim)
            else:
                axes[1, 1].set_ylim(-0.4, 0.4)
            # Add reference lines for ±Δ and ±2Δ
            for delta_val, label_text in [(gap_t0, r'$\Delta$'), (2*gap_t0, r'$2\Delta$')]:
                axes[1, 1].axvline(delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[1, 1].axvline(-delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[1, 1].text(delta_val + 0.3, 0.95, label_text, transform=axes[1, 1].get_xaxis_transform(),
                               ha='left', va='top', fontsize=18, color='gray')

            axes[1, 2].set_xlabel(r'$\omega/T_c$', fontsize=21)
            axes[1, 2].set_ylabel(r'$Im[\Delta(\omega)]/T_c$', fontsize=21)
            axes[1, 2].set_title(r'Imaginary', fontsize=23)
            axes[1, 2].set_xlim(freq_xlim)
            if ylim is not None:
                axes[1, 2].set_ylim(ylim)
            else:
                axes[1, 2].set_ylim(-0.4, 0.4)
            # Add reference lines for ±Δ and ±2Δ
            for delta_val, label_text in [(gap_t0, r'$\Delta$'), (2*gap_t0, r'$2\Delta$')]:
                axes[1, 2].axvline(delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[1, 2].axvline(-delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[1, 2].text(delta_val + 0.3, 0.95, label_text, transform=axes[1, 2].get_xaxis_transform(),
                               ha='left', va='top', fontsize=18, color='gray')

            # Configure axes - Row 2 (Current)
            axes[2, 0].set_xlabel(r'$t \cdot T_c$', fontsize=21)
            axes[2, 0].set_ylabel(r'$I(t)$', fontsize=21)
            axes[2, 0].set_title(r'Current', fontsize=23)
            if ylim is not None:
                axes[2, 0].set_ylim(ylim)

            axes[2, 1].set_xlabel(r'$\omega/T_c$', fontsize=21)
            axes[2, 1].set_ylabel(r'$Re[I(\omega)]$', fontsize=21)
            axes[2, 1].set_title(r'Real', fontsize=23)
            axes[2, 1].set_xlim(freq_xlim)
            if ylim is not None:
                axes[2, 1].set_ylim(ylim)
            # Add reference lines for ±Δ and ±2Δ
            for delta_val, label_text in [(gap_t0, r'$\Delta$'), (2*gap_t0, r'$2\Delta$')]:
                axes[2, 1].axvline(delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[2, 1].axvline(-delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[2, 1].text(delta_val + 0.3, 0.95, label_text, transform=axes[2, 1].get_xaxis_transform(),
                               ha='left', va='top', fontsize=18, color='gray')

            axes[2, 2].set_xlabel(r'$\omega/T_c$', fontsize=21)
            axes[2, 2].set_ylabel(r'$Im[I(\omega)]$', fontsize=21)
            axes[2, 2].set_title(r'Imaginary', fontsize=23)
            axes[2, 2].set_xlim(freq_xlim)
            if ylim is not None:
                axes[2, 2].set_ylim(ylim)
            # Add reference lines for ±Δ and ±2Δ
            for delta_val, label_text in [(gap_t0, r'$\Delta$'), (2*gap_t0, r'$2\Delta$')]:
                axes[2, 2].axvline(delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[2, 2].axvline(-delta_val, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)
                axes[2, 2].text(delta_val + 0.3, 0.95, label_text, transform=axes[2, 2].get_xaxis_transform(),
                               ha='left', va='top', fontsize=18, color='gray')

            # Add overall title if multiple directory jobs
            if len(directory_job_indices) > 1:
                fig.suptitle(f'Directory Job {dir_job_idx}', fontsize=21, y=0.998)

            fig.tight_layout()

            if save_plot:
                # Format plotted job indices for filename
                pulse_jobs_str = '_'.join(map(str, plot_job_indices))
                save_path = os.path.join(save_dir, f'spectral_analysis_{timestamp}_jobs{pulse_jobs_str}_dirjob{dir_job_idx}.svg')
                extended_savefig(fig, save_path, timestamp)

        else:
            # No FFT data - create 1x3 plot (time domain only)
            fig, axes = plt.subplots(1, 3, figsize=(18, 5))

            # Color cycle for different jobs using continuous colormap
            cmap = plt.get_cmap(colormap)
            colors_jobs = cmap(np.linspace(0.3, 0.9, len(plot_job_indices)))

            # Extract incoming current pulses for labeling
            incoming_current_pulses = data.get('incoming_current_pulses', None)
            field_params = data.get('field_params', [{}])

            for idx, job_idx in enumerate(plot_job_indices):
                color = colors_jobs[idx]

                # Create label from amplitude and FWHM
                label_parts = []
                try:
                    if incoming_current_pulses is not None and job_idx < len(incoming_current_pulses):
                        I_in_max = np.max(np.abs(incoming_current_pulses[job_idx]))
                        label_parts.append(r'I_{\mathrm{max}}=' + str(np.round(I_in_max, 2)))

                    if field_params is not None and job_idx < len(field_params):
                        fwhm = field_params[job_idx].get('FWHM', None)
                        if fwhm is not None:
                            label_parts.append(r'FWHM \cdot T_c=' + str(np.round(fwhm, 2)))

                    if label_parts:
                        label = '$' + ', '.join(label_parts) + '$'
                    else:
                        label = str(job_idx)
                except (IndexError, KeyError, TypeError):
                    label = str(job_idx)

                # Extract data for this job
                times_job = times[job_idx]
                gaps_job = np.abs(gap_evolution[job_idx])
                current_job = current_evolution[job_idx]
                vpot_job = vector_potential_evolution[job_idx]

                # Normalize time by T_c
                times_norm = times_job * T_c

                # Plot time domain only - reordered: vector potential, gap, current
                axes[0].plot(times_norm, vpot_job, '-', color=color, linewidth=2, label=label, alpha=0.8)
                axes[1].plot(times_norm, gaps_job / T_c, '-', color=color, linewidth=2, label=label, alpha=0.8)
                axes[2].plot(times_norm, current_job, '-', color=color, linewidth=2, label=label, alpha=0.8)

            # Configure axes - reordered: vector potential, gap, current
            axes[0].set_xlabel(r'$t \cdot T_c$', fontsize=21)
            axes[0].set_ylabel(r'$A(t)$', fontsize=21)
            axes[0].set_title(r'Vector Potential', fontsize=23)
            axes[0].legend(fontsize=13)
            if xlim is not None:
                axes[0].set_xlim(xlim)

            axes[1].set_xlabel(r'$t \cdot T_c$', fontsize=21)
            axes[1].set_ylabel(r'$|\Delta(t)|/T_c$', fontsize=21)
            axes[1].set_title(r'Gap', fontsize=23)
            if xlim is not None:
                axes[1].set_xlim(xlim)

            axes[2].set_xlabel(r'$t \cdot T_c$', fontsize=21)
            axes[2].set_ylabel(r'$I(t)$', fontsize=21)
            axes[2].set_title(r'Current', fontsize=23)
            if xlim is not None:
                axes[2].set_xlim(xlim)

            # Add overall title if multiple directory jobs
            if len(directory_job_indices) > 1:
                fig.suptitle(f'Directory Job {dir_job_idx}', fontsize=23, y=0.995)

            fig.tight_layout()

            if save_plot:
                # Format plotted job indices for filename
                pulse_jobs_str = '_'.join(map(str, plot_job_indices))
                save_path = os.path.join(save_dir, f'state_evolution_{timestamp}_jobs{pulse_jobs_str}_dirjob{dir_job_idx}.svg')
                extended_savefig(fig, save_path, timestamp)

    plt.show()

    # Return single dict if single index, list if multiple
    if len(loaded_data_list) == 1:
        return loaded_data_list[0]
    else:
        return loaded_data_list


def plot_gap_normalized_by_A2(timestamp, directory_job_index=0, plot_jobs=None,
                              cutoff=1e-6, save_plot=False, save_dir=None,
                              running_machine='laptop', colormap='Blues'):
    """
    Plot gap(ω) normalized by FT(A²(t)).

    Computes the Fourier transform of A²(t) using the same conventions as the
    gap FFT, then plots the ratio gap_fft / A²_fft. Only plots frequencies where
    |A²_fft| > cutoff to avoid division by near-zero values.

    Args:
        timestamp: Postprocessed timestamp folder with spectral analysis data
        directory_job_index: Index or list of indices of postprocessed result files (default 0)
        plot_jobs: List of job indices to plot. If None, plots all jobs.
        cutoff: Threshold for |FT(A²)|. Only plot where |FT(A²)| > cutoff (default 1e-6)
        save_plot: Whether to save plots (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: Machine type for data loading ('laptop' or 'cluster_euler')
        colormap: Colormap name for line colors (default 'Blues')

    Returns:
        dict: Contains omega, gap_normalized, and mask for each job
              Format: {job_idx: {'omega': array, 'gap_norm': array, 'mask': array}}
    """
    # Normalize directory_job_index to list
    if isinstance(directory_job_index, int):
        directory_job_indices = [directory_job_index]
    else:
        directory_job_indices = directory_job_index

    # Set up save directory if needed
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

    # Store results
    all_results = {}

    # Process each directory job index
    for dir_idx, dir_job_idx in enumerate(directory_job_indices):
        # Load postprocessed data
        data = load_postprocessed_data(timestamp, dir_job_idx, running_machine)

        # Check if FFT data available
        if 'gap_fft' not in data:
            raise ValueError(f"Spectral analysis data not found for timestamp {timestamp}, "
                           f"job {dir_job_idx}. Run postprocessor with compute_keywords=['spectral_analysis'] first.")

        # Extract data
        gap_fft = data['gap_fft']
        gap_evolution = data['gap_evolution']
        vector_potential_evolution = data['vector_potential_evolution']
        times = data['times']
        omega = data['omega']
        T_c = data['T_c'][0]

        # Get gap at t=0 from first job for reference lines
        gap_0 = np.abs(gap_evolution[0][0])
        gap_0_norm = gap_0 / T_c

        # Determine which jobs to plot
        if plot_jobs is None:
            plot_job_indices = range(len(gap_fft))
        else:
            plot_job_indices = plot_jobs

        # Create figure with 2 subplots (real and imaginary parts)
        fig, (ax_re, ax_im) = plt.subplots(1, 2, figsize=(16, 6))

        # Color cycle using continuous colormap
        cmap = plt.get_cmap(colormap)
        colors_jobs = cmap(np.linspace(0.3, 0.9, len(plot_job_indices)))

        # Track valid omega range across all jobs
        omega_min = np.inf
        omega_max = -np.inf

        for idx, job_idx in enumerate(plot_job_indices):
            color = colors_jobs[idx]
            label = str(job_idx)

            # Extract data for this job
            times_job = times[job_idx]
            vpot_job = vector_potential_evolution[job_idx]
            gap_fft_job = gap_fft[job_idx]
            omega_job = omega[job_idx]

            # Compute A²(t)
            A_squared = vpot_job ** 2

            # Compute FT(A²(t)) using same conventions as gap FFT
            dt = times_job[1] - times_job[0]
            N_t = len(times_job)

            # Frequency grid (should match omega_job from data)
            freq = np.fft.fftfreq(N_t, d=dt)
            omega_check = 2 * np.pi * freq

            # Phase correction (same as in spectral analysis)
            t_center_idx = np.argmax(np.abs(vpot_job))
            t_center = times_job[t_center_idx]
            phase_correction = np.exp(-1j * omega_check * t_center)

            # Compute FT(A²(t))
            A2_fft_raw = np.fft.fft(A_squared) * dt
            A2_fft_corrected = A2_fft_raw * phase_correction
            A2_fft_shifted = np.fft.fftshift(A2_fft_corrected)

            # Compute normalized gap
            gap_normalized = gap_fft_job / A2_fft_shifted

            # Apply cutoff: only keep frequencies where |FT(A²)| > cutoff
            mask = np.abs(A2_fft_shifted) > cutoff

            # Normalize omega by T_c
            omega_norm = omega_job / T_c

            # Store results
            all_results[job_idx] = {
                'omega': omega_norm[mask],
                'gap_norm': gap_normalized[mask],
                'mask': mask,
                'A2_fft': A2_fft_shifted
            }

            # Update valid omega range
            if np.any(mask):
                omega_min = min(omega_min, np.min(omega_norm[mask]))
                omega_max = max(omega_max, np.max(omega_norm[mask]))

            # Plot real and imaginary parts separately
            ax_re.plot(omega_norm[mask], np.real(gap_normalized[mask]), '-',
                      color=color, linewidth=2, label=label, alpha=0.8)
            ax_im.plot(omega_norm[mask], np.imag(gap_normalized[mask]), '-',
                      color=color, linewidth=2, label=label, alpha=0.8)

        # Add vertical reference lines for gap(t=0) and 2*gap(t=0) to both plots
        for ax in [ax_re, ax_im]:
            ax.axvline(gap_0_norm, color='gray', linestyle=':', linewidth=2,
                      label=r'$\Delta_0/T_c$', alpha=0.7)
            ax.axvline(2*gap_0_norm, color='darkgray', linestyle=':', linewidth=2,
                      label=r'$2\Delta_0/T_c$', alpha=0.7)
            ax.axvline(-gap_0_norm, color='gray', linestyle=':', linewidth=2, alpha=0.7)
            ax.axvline(-2*gap_0_norm, color='darkgray', linestyle=':', linewidth=2, alpha=0.7)

        # Configure real part axes
        ax_re.set_xlabel(r'$\omega/T_c$', fontsize=21)
        ax_re.set_ylabel(r'$Re[\tilde{\Delta}(\omega) / FT[A^2(t)]]$', fontsize=21)
        ax_re.set_title(r' mathrm{(a) Real Part}', fontsize=23)

        # Configure imaginary part axes
        ax_im.set_xlabel(r'$\omega/T_c$', fontsize=21)
        ax_im.set_ylabel(r'$Im[\tilde{\Delta}(\omega) / FT[A^2(t)]]$', fontsize=21)
        ax_im.set_title(r' mathrm{(b) Imaginary Part}', fontsize=23)

        # Set xlim based on valid omega range (where |FT(A²)| > cutoff)
        if omega_min < omega_max:
            # Add small margin (5%)
            margin = 0.05 * (omega_max - omega_min)
            for ax in [ax_re, ax_im]:
                ax.set_xlim(omega_min - margin, omega_max + margin)

        # Add legends
        ax_re.legend(fontsize=12)
        ax_im.legend(fontsize=12)

        # Add overall title if multiple directory jobs
        if len(directory_job_indices) > 1:
            fig.suptitle(f'Directory Job {dir_job_idx}', fontsize=23, y=0.995)

        fig.tight_layout()

        if save_plot:
            pulse_jobs_str = '_'.join(map(str, plot_job_indices))
            save_path = os.path.join(save_dir,
                                    f'gap_norm_A2_{timestamp}_jobs{pulse_jobs_str}_dirjob{dir_job_idx}.svg')
            extended_savefig(fig, save_path, timestamp)

    plt.show()

    return all_results


def plot_two_time_greens_function(timestamp, directory_job_index=None, component='gr',
                                   tau_component=None, plot_part='both', vmin=None, vmax=None,
                                   cmap='RdBu_r', t_lim=None, tprime_lim=None,
                                   save_plot=False, save_dir=None, running_machine='laptop'):
    """
    Plot two-time Green's function (gr or gk) Pauli components.

    Green's function has shape (2, 2, N_t, N_t) where N_t x N_t are the two time dimensions.
    Plots either all 4 Pauli components or a specific component.

    Args:
        timestamp: Timestamp folder identifier (raw simulation data, not postprocessed)
        directory_job_index: Index of result file to load. If None, will ask user (default None)
        component: Which Green's function to plot: 'gr' or 'gk' (default 'gr')
        tau_component: Which Pauli component to plot (0=I, 1=X, 2=Y, 3=Z).
                      If None, plots all 4 components (default None)
        plot_part: Which part to plot: 'real', 'imag', or 'both' (default 'both')
        vmin, vmax: Optional colorbar limits (if None, auto-scale per component)
        cmap: Colormap to use (default 'RdBu_r' for diverging red-blue)
        t_lim: Optional tuple (t_min, t_max) to zoom into specific t range
        tprime_lim: Optional tuple (tprime_min, tprime_max) to zoom into specific t' range
        save_plot: Whether to save the plot (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: 'laptop' or 'cluster_euler'

    Returns:
        dict: Loaded data dictionary
    """
    # Initialize path management if needed
    if not hasattr(path_management, 'project_data'):
        path_management.initialize(project_name='psBQP-keldysh')

    # Normalize directory_job_index (handle if passed as list)
    if isinstance(directory_job_index, list):
        if len(directory_job_index) == 1:
            directory_job_index = directory_job_index[0]
        else:
            raise ValueError(f"directory_job_index must be a single integer, got list with {len(directory_job_index)} elements")

    # If job index not provided, check how many jobs exist and ask user
    if directory_job_index is None:
        simulation_data_path = path_management.default_simulation_data_path(running_machine=running_machine)
        timestamp_dir = os.path.join(simulation_data_path, str(timestamp))

        # Check archive if not in simulation data path
        if not os.path.exists(timestamp_dir):
            archive_path = path_management.default_autoarchive_path(running_machine=running_machine)
            timestamp_dir = os.path.join(archive_path, str(timestamp))

        if not os.path.exists(timestamp_dir):
            raise FileNotFoundError(f"Timestamp directory not found: {timestamp}")

        # Count available job files
        job_files = [f for f in os.listdir(timestamp_dir) if f.startswith('result_') and f.endswith('.pkl')]
        num_jobs = len(job_files)

        if num_jobs == 0:
            raise FileNotFoundError(f"No result files found in {timestamp_dir}")
        elif num_jobs == 1:
            directory_job_index = 0
        else:
            # Ask user which job to plot
            print(f"Found {num_jobs} jobs in timestamp {timestamp}")
            directory_job_index = int(input(f"Enter job index (0-{num_jobs-1}): "))

    # Construct path to raw result file
    simulation_data_path = path_management.default_simulation_data_path(running_machine=running_machine)
    result_file = os.path.join(simulation_data_path, str(timestamp),
                               path_management.relative_path_raw_result_file().format(directory_job_index))

    # Check archive path if not found
    if not os.path.exists(result_file):
        archive_path = path_management.default_autoarchive_path(running_machine=running_machine)
        result_file = os.path.join(archive_path, str(timestamp),
                                   path_management.relative_path_raw_result_file().format(directory_job_index))

    if not os.path.exists(result_file):
        raise FileNotFoundError(f"Data file not found for timestamp {timestamp}, job {directory_job_index}")

    # Load the data
    with open(result_file, 'rb') as f:
        data = pickle.load(f)

    # Extract the Green's function
    final_state = data['final_state']
    if component == 'gr':
        greens_function = final_state.gr
    elif component == 'gk':
        greens_function = final_state.gk
    else:
        raise ValueError(f"component must be 'gr' or 'gk', got '{component}'")

    # greens_function.data has shape (2, 2, N_t, N_t)
    # Import locally to create NambuKeldyshTensor
    from nambu_keldysh_class import NambuKeldyshTensor

    # Get time grid from state
    T_max = final_state.T_max
    N_t = greens_function.data.shape[-1]
    time_grid = np.linspace(0, T_max, N_t)

    # Pauli component labels
    pauli_labels = ['I (Identity)', 'X ($\\sigma_x$)', 'Y ($\\sigma_y$)', 'Z ($\\sigma_z$)']

    # Time extent for imshow (smallest times in top-left corner)
    t_min, t_max = time_grid[0], time_grid[-1]
    extent = [t_min, t_max, t_max, t_min]  # [left, right, bottom, top] with origin='upper'

    if tau_component is not None:
        # Extract Pauli component using trace (divide by 2 for normalization)
        component_data = greens_function.trace(pauli_index=tau_component) / 2

        # Component name with superscript notation (g^r or g^k) and time arguments
        superscript = 'r' if component == 'gr' else 'k'
        component_prefix = r"g^{" + superscript + r"}_{" + str(tau_component) + r"}(t, t')"

        if plot_part == 'both':
            # Plot both real and imaginary in 1x2 grid
            fig, (ax_real, ax_imag) = plt.subplots(1, 2, figsize=(12, 5))

            # Real part
            im_real = ax_real.imshow(np.real(component_data), aspect='auto', origin='upper',
                                     extent=extent, cmap=cmap, vmin=vmin, vmax=vmax)
            ax_real.set_title(r"$\Re[" + component_prefix + r"]$", fontsize=21)
            ax_real.set_xlabel(r"$t \cdot T_c$", fontsize=18)
            ax_real.set_ylabel(r"$t' \cdot T_c$", fontsize=18)
            if t_lim is not None:
                ax_real.set_xlim(t_lim)
            if tprime_lim is not None:
                ax_real.set_ylim(tprime_lim[1], tprime_lim[0])
            plt.colorbar(im_real, ax=ax_real, fraction=0.046, pad=0.04)

            # Imaginary part
            im_imag = ax_imag.imshow(np.imag(component_data), aspect='auto', origin='upper',
                                     extent=extent, cmap=cmap, vmin=vmin, vmax=vmax)
            ax_imag.set_title(r"$\Im[" + component_prefix + r"]$", fontsize=21)
            ax_imag.set_xlabel(r"$t \cdot T_c$", fontsize=18)
            ax_imag.set_ylabel(r"$t' \cdot T_c$", fontsize=18)
            if t_lim is not None:
                ax_imag.set_xlim(t_lim)
            if tprime_lim is not None:
                ax_imag.set_ylim(tprime_lim[1], tprime_lim[0])
            plt.colorbar(im_imag, ax=ax_imag, fraction=0.046, pad=0.04)

        else:
            # Plot only real or imaginary in single plot
            fig, ax = plt.subplots(1, 1, figsize=(8, 6))

            if plot_part == 'real':
                plot_data = np.real(component_data)
                part_symbol = r"\Re"
            elif plot_part == 'imag':
                plot_data = np.imag(component_data)
                part_symbol = r"\Im"
            else:
                raise ValueError("plot_part must be 'real', 'imag', or 'both', got '" + str(plot_part) + "'")

            im = ax.imshow(plot_data, aspect='auto', origin='upper',
                          extent=extent, cmap=cmap, vmin=vmin, vmax=vmax)
            ax.set_title(r"$" + part_symbol + r"[" + component_prefix + r"]$", fontsize=18)
            ax.set_xlabel(r"$t \cdot T_c$", fontsize=18)
            ax.set_ylabel(r"$t' \cdot T_c$", fontsize=18)
            if t_lim is not None:
                ax.set_xlim(t_lim)
            if tprime_lim is not None:
                ax.set_ylim(tprime_lim[1], tprime_lim[0])
            plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    else:
        # Plot all 4 Pauli components in 2x4 grid
        fig, axes = plt.subplots(2, 4, figsize=(18, 9))

        for pauli_idx in range(4):
            # Extract Pauli component using trace (divide by 2 for normalization)
            component_data = greens_function.trace(pauli_index=pauli_idx) / 2

            # Real part (top row)
            ax_real = axes[0, pauli_idx]
            im_real = ax_real.imshow(np.real(component_data), aspect='auto', origin='upper',
                                     extent=extent, cmap=cmap, vmin=vmin, vmax=vmax)
            ax_real.set_title(f"{pauli_labels[pauli_idx]} - Real", fontsize=12)
            if pauli_idx == 0:
                ax_real.set_ylabel(r"$t' \cdot T_c$", fontsize=18, fontweight='bold')
            else:
                ax_real.set_ylabel(r"$t' \cdot T_c$", fontsize=21)
            if t_lim is not None:
                ax_real.set_xlim(t_lim)
            if tprime_lim is not None:
                ax_real.set_ylim(tprime_lim[1], tprime_lim[0])
            plt.colorbar(im_real, ax=ax_real, fraction=0.046, pad=0.04)

            # Imaginary part (bottom row)
            ax_imag = axes[1, pauli_idx]
            im_imag = ax_imag.imshow(np.imag(component_data), aspect='auto', origin='upper',
                                     extent=extent, cmap=cmap, vmin=vmin, vmax=vmax)
            ax_imag.set_title(f"{pauli_labels[pauli_idx]} - Imaginary", fontsize=12)
            ax_imag.set_xlabel(r"$t \cdot T_c$", fontsize=18, fontweight='bold')
            if pauli_idx == 0:
                ax_imag.set_ylabel(r"$t' \cdot T_c$", fontsize=18, fontweight='bold')
            else:
                ax_imag.set_ylabel(r"$t' \cdot T_c$", fontsize=21)
            if t_lim is not None:
                ax_imag.set_xlim(t_lim)
            if tprime_lim is not None:
                ax_imag.set_ylim(tprime_lim[1], tprime_lim[0])
            plt.colorbar(im_imag, ax=ax_imag, fraction=0.046, pad=0.04)

        # Overall title
        component_name = "Retarded" if component == 'gr' else "Keldysh"
        title = f"{component_name} Green's Function - All Pauli Components"
        fig.suptitle(title, fontsize=21, fontweight='bold', y=0.995)

    fig.tight_layout()

    # Save if requested
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

        if tau_component is not None:
            part_str = f'_{plot_part}' if plot_part != 'both' else ''
            save_path = os.path.join(save_dir,
                                    f'{component}_two_time_{timestamp}_job{directory_job_index}_pauli{tau_component}{part_str}.svg')
        else:
            save_path = os.path.join(save_dir,
                                    f'{component}_two_time_{timestamp}_job{directory_job_index}_all.svg')
        extended_savefig(fig, save_path, timestamp)

    plt.show()

    return data


def plot_static_observables(timestamp, directory_job_index=0, parameter=None,
                            save_plot=False, save_dir=None, running_machine='laptop',
                            colormap='Blues', marker='o', ylim_gap=None, ylim_current=None):
    """
    Plot gap and current vs specified parameter from static postprocessed data.

    Creates a 2-panel plot showing time-averaged gap (left) and current (right).
    Data structure: Each job has ONE averaged gap, current, and vector potential value.

    Args:
        timestamp: Postprocessed timestamp folder (must have been processed with 'static' keyword)
        directory_job_index: Index of postprocessed result file to load (default 0)
        parameter: What to plot on X-axis (default None = auto-detect or 'vector_potential')
                  - None: Auto-detect which parameter varies across jobs
                  - 'temperature': X-axis = T/T_c (each job = different temperature)
                  - 'field_params:amplitude': X-axis = A (each job = different amplitude)
                  - Other field_params keys supported
        save_plot: Whether to save plot (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: Machine type for data loading ('laptop' or 'cluster_euler')
        colormap: Colormap name for marker colors (default 'Blues')
        marker: Marker style (default 'o')
        ylim_gap: Tuple (ymin, ymax) for gap axis limits (default None = auto)
        ylim_current: Tuple (ymin, ymax) for current axis limits (default None = auto)

    Returns:
        dict: Loaded postprocessed data with keys:
            - 'system_parameters': List of system parameter dicts (one per job)
            - 'field_params': List of field parameter dicts (one per job)
            - 'averaged_gaps': Array of averaged gap values
            - 'averaged_currents': Array of averaged current values
            - 'averaged_vector_potentials': Array of averaged vector potential values

    Examples:
        # Auto-detect parameter and plot
        plot_static_observables(timestamp, directory_job_index=0)

        # Plot gap and current vs temperature
        plot_static_observables(timestamp, directory_job_index=0, parameter='temperature')

        # Plot gap and current vs field amplitude with custom y-limits
        plot_static_observables(timestamp, directory_job_index=0,
                               parameter='field_params:amplitude',
                               ylim_gap=(0, 1.5), ylim_current=(0, 0.5))
    """
    # Load postprocessed data
    data = load_postprocessed_data(timestamp, directory_job_index, running_machine)

    # Extract data arrays (each job = one point)
    averaged_gaps = data['averaged_gaps']
    averaged_currents = data['averaged_currents']
    averaged_vector_potentials = data['averaged_vector_potentials']
    system_parameters_list = data['system_parameters']
    field_params_list = data.get('field_params', [{}] * len(system_parameters_list))

    # Auto-detect parameter if not specified
    if parameter is None:
        parameter = _auto_detect_parameter(system_parameters_list, field_params_list)

    # Extract X-axis values based on parameter
    if parameter == 'temperature':
        # Each job has different temperature
        x_values = np.array([sp['temperature'] for sp in system_parameters_list])
        T_c = system_parameters_list[0].get('critical_temperature', 1.0)
        x_normalized = x_values  # Already in units of T_c
        xlabel = r'$T/T_c$'
    elif parameter.startswith('field_params:'):
        # Extract field parameter
        key = parameter.split(':', 1)[1]
        x_values = np.array([fp.get(key, 0) for fp in field_params_list])
        x_normalized = x_values
        xlabel = _format_parameter_label(parameter)
    elif parameter in system_parameters_list[0]:
        # Extract from system parameters
        x_values = np.array([sp.get(parameter, 0) for sp in system_parameters_list])
        x_normalized = x_values
        xlabel = _format_parameter_label(parameter)
    else:
        raise ValueError(f"Unknown parameter: {parameter}")

    # Get normalization constants from first job
    T_c = system_parameters_list[0].get('critical_temperature', 1.0)
    sigma_n = system_parameters_list[0].get('normal_conductivity', 1.0)

    # Normalize observables
    gap_normalized = np.abs(averaged_gaps) / T_c

    # For current normalization, need to handle vector potential scaling
    # Each job has one A value, so use max across all jobs as A_0
    A_0 = np.max(np.abs(averaged_vector_potentials))
    if A_0 < 1e-12:
        A_0 = 1.0
    current_normalized = np.abs(averaged_currents) / (sigma_n * A_0 * T_c)

    # Create figure with 2 subplots
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    ax_gap, ax_current = axes

    # Get colormap
    cmap = plt.get_cmap(colormap)
    color = cmap(0.6)

    # ========== Plot gap vs parameter ==========
    ax_gap.plot(x_normalized, gap_normalized, marker=marker,
                color=color, linewidth=3, markersize=8, alpha=0.8)
    ax_gap.set_xlabel(xlabel, fontsize=21)
    ax_gap.set_ylabel(r'$|\Delta|/T_c$', fontsize=21)
    ax_gap.set_title(r'Gap vs ' + xlabel.strip('$'), fontsize=23)
    if ylim_gap is not None:
        ax_gap.set_ylim(ylim_gap)

    # ========== Plot current vs parameter ==========
    ax_current.plot(x_normalized, current_normalized, marker=marker,
                   color=color, linewidth=3, markersize=8, alpha=0.8)
    ax_current.set_xlabel(xlabel, fontsize=21)
    ax_current.set_ylabel(r'$J_s/(\sigma_n A_0 T_c)$', fontsize=21)
    ax_current.set_title(r'Current vs ' + xlabel.strip('$'), fontsize=23)
    if ylim_current is not None:
        ax_current.set_ylim(ylim_current)

    # Add horizontal line at critical current if plotting vs A
    if not parameter == 'temperature' and not parameter.startswith('field_params'):
        J_c = np.max(current_normalized)
        ax_current.axhline(y=J_c, color='gray', linestyle=':', linewidth=2)
        ax_current.text(0.75 * np.max(x_normalized), J_c * 0.98, r'$J_c$',
                       fontsize=18, verticalalignment='top')

    fig.tight_layout()

    # Set up save directory if needed
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

        # Format filename
        param_str = parameter.replace(':', '_').replace(' ', '_')
        save_path = os.path.join(save_dir, f'static_observables_{timestamp}_job{directory_job_index}_vs_{param_str}.svg')
        extended_savefig(fig, save_path, timestamp)

    plt.show()

    return data


def _auto_detect_parameter(system_parameters_list, field_params_list):
    """
    Auto-detect which parameter varies across jobs.

    Args:
        system_parameters_list: List of system parameter dicts
        field_params_list: List of field parameter dicts

    Returns:
        str: Parameter name (e.g., 'temperature', 'field_params:amplitude')
    """
    n_jobs = len(system_parameters_list)
    if n_jobs <= 1:
        return 'temperature'  # Default if only one job

    # Check common parameters in system_parameters
    for key in ['temperature', 'eta']:
        values = [system_parameters_list[i].get(key, None) for i in range(n_jobs)]
        if len(set(values)) > 1:  # More than one unique value
            return key

    # Check common parameters in field_params
    for key in ['amplitude', 'FWHM', 'frequency']:
        values = [field_params_list[i].get(key, None) for i in range(n_jobs)]
        if len(set(values)) > 1:
            return f'field_params:{key}'

    # Default fallback
    return 'temperature'


def _format_parameter_label(parameter):
    """
    Format parameter name for plot labels.

    Args:
        parameter: Parameter name string

    Returns:
        str: LaTeX-formatted label
    """
    if parameter == 'temperature':
        return r'$T/T_c$'
    elif parameter == 'eta':
        return r'$\eta/T_c$'
    elif parameter == 'vector_potential':
        return r'$A$'
    elif parameter.startswith('field_params:'):
        key = parameter.split(':', 1)[1]
        if key == 'amplitude':
            return r'$A_0$'
        elif key == 'FWHM':
            return r'$\mathrm{FWHM}\cdot T_c$'
        elif key == 'frequency':
            return r'$\omega/T_c$'
        else:
            return r'$' + key + r'$'
    elif parameter.startswith('system_parameters:'):
        key = parameter.split(':', 1)[1]
        return r'$' + key + r'$'
    else:
        return r'$' + parameter + r'$'


def plot_consistency_checks(timestamp, directory_job_index=0, parameter=None,
                           save_plot=False, save_dir=None, running_machine='laptop',
                           colormap='Reds', marker='o', show_total=True, show_components=False,
                           ylim=None, yscale='log'):
    """
    Plot FDT and normalization check errors vs parameter from static postprocessed data.

    Creates a 3-panel plot showing g^R normalization, Keldysh normalization, and FDT errors.
    Each error is evaluated at the last row [-1, :] and last column [:, -1] position.

    Args:
        timestamp: Postprocessed timestamp folder (must have 'static' data with consistency checks)
        directory_job_index: Index of postprocessed result file to load (default 0)
        parameter: What to plot on X-axis (default None = auto-detect)
                  - None: Auto-detect which parameter varies across jobs
                  - 'temperature': X-axis = T/T_c
                  - 'field_params:amplitude': X-axis = A
        save_plot: Whether to save plot (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: Machine type for data loading ('laptop' or 'cluster_euler')
        colormap: Colormap name for plot colors (default 'Reds')
        marker: Marker style (default 'o')
        show_total: Show total error (sum over all Pauli components) (default True)
        show_components: Show individual Pauli components (default False)
        ylim: Tuple (ymin, ymax) for y-axis limits (default None = auto)
        yscale: Y-axis scale ('log' or 'linear', default 'log')

    Returns:
        dict: Loaded postprocessed data with consistency check arrays

    Examples:
        # Plot consistency checks vs temperature (log scale)
        plot_consistency_checks(timestamp, parameter='temperature')

        # Plot with individual Pauli components visible
        plot_consistency_checks(timestamp, parameter='temperature',
                               show_total=True, show_components=True)

        # Linear scale with custom y-limits
        plot_consistency_checks(timestamp, parameter='field_params:amplitude',
                               yscale='linear', ylim=(0, 1e-3))
    """
    # Load postprocessed data
    data = load_postprocessed_data(timestamp, directory_job_index, running_machine)

    # Extract consistency check arrays
    gr_errors = data.get('gr_normalization_errors', None)  # Shape (N_jobs, 4)
    gk_errors = data.get('gk_normalization_errors', None)  # Shape (N_jobs, 4)
    fdt_errors = data.get('fdt_errors', None)  # Shape (N_jobs, 4)

    if gr_errors is None or gk_errors is None or fdt_errors is None:
        raise ValueError("Consistency check data not found. Make sure postprocessor was run with consistency checks enabled.")

    system_parameters_list = data['system_parameters']
    field_params_list = data.get('field_params', [{}] * len(system_parameters_list))

    # Auto-detect parameter if not specified
    if parameter is None:
        parameter = _auto_detect_parameter(system_parameters_list, field_params_list)

    # Extract X-axis values based on parameter
    if parameter == 'temperature':
        x_values = np.array([sp['temperature'] for sp in system_parameters_list])
        T_c = system_parameters_list[0].get('critical_temperature', 1.0)
        x_normalized = x_values
        xlabel = r'$T/T_c$'
    elif parameter.startswith('field_params:'):
        key = parameter.split(':', 1)[1]
        x_values = np.array([fp.get(key, 0) for fp in field_params_list])
        x_normalized = x_values
        xlabel = _format_parameter_label(parameter)
    elif parameter in system_parameters_list[0]:
        x_values = np.array([sp.get(parameter, 0) for sp in system_parameters_list])
        x_normalized = x_values
        xlabel = _format_parameter_label(parameter)
    else:
        raise ValueError(f"Unknown parameter: {parameter}")

    # Compute total errors (L2 norm over all Pauli components)
    gr_total = np.sqrt(np.sum(gr_errors**2, axis=1))  # Shape (N_jobs,)
    gk_total = np.sqrt(np.sum(gk_errors**2, axis=1))  # Shape (N_jobs,)
    fdt_total = np.sqrt(np.sum(fdt_errors**2, axis=1))  # Shape (N_jobs,)

    # Create figure with 3 subplots
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    ax_gr, ax_gk, ax_fdt = axes

    # Get colormap
    cmap = plt.get_cmap(colormap)
    pauli_labels = [r'$\tau_0$', r'$\tau_1$', r'$\tau_2$', r'$\tau_3$']
    pauli_colors = [cmap(0.3), cmap(0.5), cmap(0.7), cmap(0.9)]

    # ========== Plot g^R normalization errors ==========
    if show_total:
        ax_gr.plot(x_normalized, gr_total, marker=marker, color=cmap(0.8),
                  linewidth=3, markersize=8, alpha=0.9, label='Total', zorder=10)
    if show_components:
        for pauli_idx in range(4):
            ax_gr.plot(x_normalized, gr_errors[:, pauli_idx], marker=marker,
                      color=pauli_colors[pauli_idx], linewidth=2, markersize=6,
                      alpha=0.7, label=pauli_labels[pauli_idx], linestyle='--')

    ax_gr.set_xlabel(xlabel, fontsize=21)
    ax_gr.set_ylabel(r'$g^R$ Normalization Error', fontsize=21)
    ax_gr.set_title(r'$g^R$ Normalization', fontsize=23)
    ax_gr.set_yscale(yscale)
    if ylim is not None:
        ax_gr.set_ylim(ylim)
    if show_total and show_components:
        ax_gr.legend(fontsize=14, framealpha=0.9)
    ax_gr.grid(True, alpha=0.3)

    # ========== Plot Keldysh normalization errors ==========
    if show_total:
        ax_gk.plot(x_normalized, gk_total, marker=marker, color=cmap(0.8),
                  linewidth=3, markersize=8, alpha=0.9, label='Total', zorder=10)
    if show_components:
        for pauli_idx in range(4):
            ax_gk.plot(x_normalized, gk_errors[:, pauli_idx], marker=marker,
                      color=pauli_colors[pauli_idx], linewidth=2, markersize=6,
                      alpha=0.7, label=pauli_labels[pauli_idx], linestyle='--')

    ax_gk.set_xlabel(xlabel, fontsize=21)
    ax_gk.set_ylabel(r'$g^K$ Normalization Error', fontsize=21)
    ax_gk.set_title(r'Keldysh Normalization', fontsize=23)
    ax_gk.set_yscale(yscale)
    if ylim is not None:
        ax_gk.set_ylim(ylim)
    if show_total and show_components:
        ax_gk.legend(fontsize=14, framealpha=0.9)
    ax_gk.grid(True, alpha=0.3)

    # ========== Plot FDT errors ==========
    if show_total:
        ax_fdt.plot(x_normalized, fdt_total, marker=marker, color=cmap(0.8),
                   linewidth=3, markersize=8, alpha=0.9, label='Total', zorder=10)
    if show_components:
        for pauli_idx in range(4):
            ax_fdt.plot(x_normalized, fdt_errors[:, pauli_idx], marker=marker,
                       color=pauli_colors[pauli_idx], linewidth=2, markersize=6,
                       alpha=0.7, label=pauli_labels[pauli_idx], linestyle='--')

    ax_fdt.set_xlabel(xlabel, fontsize=21)
    ax_fdt.set_ylabel(r'FDT Error', fontsize=21)
    ax_fdt.set_title(r'Fluctuation-Dissipation', fontsize=23)
    ax_fdt.set_yscale(yscale)
    if ylim is not None:
        ax_fdt.set_ylim(ylim)
    if show_total and show_components:
        ax_fdt.legend(fontsize=14, framealpha=0.9)
    ax_fdt.grid(True, alpha=0.3)

    fig.tight_layout()

    # Set up save directory if needed
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

        # Format filename
        param_str = parameter.replace(':', '_').replace(' ', '_')
        save_path = os.path.join(save_dir, f'consistency_checks_{timestamp}_job{directory_job_index}_vs_{param_str}.svg')
        extended_savefig(fig, save_path, timestamp)

    plt.show()

    return data


def plot_xy_data(x_data_list, y_data_list, label_list=None,
                 xlabel=None, ylabel=None, title=None,
                 colormap='Blues', marker='', linestyle='-', linewidth=3, markersize=6,
                 figsize=(10, 6), xlim=None, ylim=None,
                 save_plot=False, save_dir=None, save_name='xy_plot.svg'):
    """
    Plot x-y data with consistent styling.

    Creates a plot with multiple datasets using the same style as other plotting functions.

    Args:
        x_data_list: List of x-data arrays (or single array for one dataset)
        y_data_list: List of y-data arrays (or single array for one dataset)
        label_list: List of labels for each dataset (optional)
        xlabel: X-axis label (LaTeX string, optional)
        ylabel: Y-axis label (LaTeX string, optional)
        title: Plot title (LaTeX string, optional)
        colormap: Colormap name for line colors (default 'Blues')
        marker: Marker style (default '')
        linestyle: Line style (default '-')
        linewidth: Line width (default 3)
        markersize: Marker size (default 6)
        figsize: Figure size tuple (default (10, 6))
        xlim: Tuple (xmin, xmax) for x-axis limits (default None = auto)
        ylim: Tuple (ymin, ymax) for y-axis limits (default None = auto)
        save_plot: Whether to save plot (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        save_name: Filename for saved plot (default 'xy_plot.svg')

    Returns:
        fig, ax: Matplotlib figure and axes objects
    """
    # Normalize inputs to lists
    if not isinstance(x_data_list, list):
        x_data_list = [x_data_list]
    if not isinstance(y_data_list, list):
        y_data_list = [y_data_list]

    n_datasets = len(x_data_list)

    # Create default labels if not provided
    if label_list is None:
        label_list = [None] * n_datasets
    elif not isinstance(label_list, list):
        label_list = [label_list]

    # Create figure
    fig, ax = plt.subplots(1, 1, figsize=figsize)

    # Get colors from colormap
    cmap = plt.get_cmap(colormap)
    colors = cmap(np.linspace(0.3, 0.9, n_datasets))

    # Plot each dataset
    for idx in range(n_datasets):
        x_data = x_data_list[idx]
        y_data = y_data_list[idx]
        label = label_list[idx]
        color = colors[idx]

        ax.plot(x_data, y_data, linestyle=linestyle, marker=marker,
                color=color, linewidth=linewidth, markersize=markersize,
                label=label, alpha=0.8)

    # Set labels and title
    if xlabel is not None:
        ax.set_xlabel(xlabel, fontsize=21)
    if ylabel is not None:
        ax.set_ylabel(ylabel, fontsize=21)
    if title is not None:
        ax.set_title(title, fontsize=23)

    # Add legend if labels were provided
    if any(label is not None for label in label_list):
        ax.legend(fontsize=15)

    # Set axis limits if provided
    if xlim is not None:
        ax.set_xlim(xlim)
    if ylim is not None:
        ax.set_ylim(ylim)

    fig.tight_layout()

    # Save plot if requested
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

        save_path = os.path.join(save_dir, save_name)
        fig.savefig(save_path, bbox_inches='tight', dpi=300)

    plt.show()

    return fig, ax
