"""
Analysis and plotting tools for postprocessed Keldysh data.

Loads and visualizes data generated by run_postprocessor.py
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import pickle

from demler_tools.file_manager import io, path_management
from demler_tools.data_analysis.image_file_tools import extended_savefig

sys.path.append(os.path.dirname(os.path.abspath(__file__)))


def load_postprocessed_data(timestamp, directory_job_index=0, running_machine='laptop'):
    """
    Load postprocessed data from timestamp folder.

    Args:
        timestamp: Timestamp folder identifier
        directory_job_index: Index of postprocessed result file to load (default 0)
        running_machine: 'laptop' or 'cluster_euler'

    Returns:
        dict: Postprocessed data dictionary with keys from run_postprocessor.py output
    """
    if not hasattr(path_management, 'project_data'):
        path_management.initialize(project_name='psBQP-keldysh')

    simulation_data_path = path_management.default_simulation_data_path(running_machine=running_machine)
    result_file = os.path.join(simulation_data_path, str(timestamp),
                               path_management.relative_path_raw_result_file().format(directory_job_index))

    # Check archive path if not found in simulation data path
    if not os.path.exists(result_file):
        archive_path = path_management.default_autoarchive_path(running_machine=running_machine)
        result_file = os.path.join(archive_path, str(timestamp),
                                   path_management.relative_path_raw_result_file().format(directory_job_index))

    if not os.path.exists(result_file):
        raise FileNotFoundError(f"Postprocessed data file not found for timestamp {timestamp}, job {directory_job_index}")

    with open(result_file, 'rb') as f:
        data = pickle.load(f)

    return data


def plot_transmitivity_results(timestamp, directory_job_index=0, job_indices=None, plot_pulses=False,
                               save_plot=False, save_dir=None, running_machine='laptop'):
    """
    Plot transmitivity analysis from postprocessed data.

    Creates a 2-panel transmitivity plot and optionally a 2x2 time trace plot.

    Args:
        timestamp: Postprocessed timestamp folder
        directory_job_index: Index or list of indices of postprocessed result files to load (default 0)
        job_indices: Deprecated parameter (kept for backward compatibility, not used)
        plot_pulses: If False, no pulse plots. If True, plots all jobs. If list, plots only specified job indices.
        save_plot: Whether to save plots (default False)
        save_dir: Directory for plots (default None uses Figures/ in project folder)
        running_machine: Machine type for data loading ('laptop' or 'cluster_euler')

    Returns:
        dict or list: Loaded postprocessed data (dict if single index, list if multiple)
    """
    # Normalize directory_job_index to list
    if isinstance(directory_job_index, int):
        directory_job_indices = [directory_job_index]
    else:
        directory_job_indices = directory_job_index

    # Create transmitivity plots (2 panels)
    fig_trans, axes = plt.subplots(1, 2, figsize=(12, 5))
    ax_trans, ax_jmax = axes

    # Color cycle for different directory job indices
    colors = plt.cm.tab10(np.linspace(0, 1, len(directory_job_indices)))

    # Store loaded data
    loaded_data_list = []

    # Plot each directory job index
    for idx, dir_job_idx in enumerate(directory_job_indices):
        color = colors[idx]

        # Load postprocessed data
        data = load_postprocessed_data(timestamp, dir_job_idx, running_machine)
        loaded_data_list.append(data)

        # Extract data arrays
        I_in_max_array = data['incoming_current_amplitudes']
        J_max_array = data['transmitted_current_amplitudes']
        transmitivity_array = data['transmitivity']

        # Extract parameters from first job for legend
        system_params = data['system_parameters'][0]
        field_params = data.get('field_params', [{}])[0]

        temperature = system_params.get('temperature', None)
        eta = system_params.get('eta', None)
        fwhm = field_params.get('FWHM', None)

        # Build legend label with available parameters (using LaTeX formatting)
        label_parts = []
        if len(directory_job_indices) > 1:
            label_parts.append(f'Job {dir_job_idx}')
        if temperature is not None:
            label_parts.append(f'$T={temperature:.3g}$')
        if eta is not None:
            label_parts.append(f'$\\eta={eta:.3g}$')
        if fwhm is not None:
            label_parts.append(f'FWHM$={fwhm:.3g}$')
        legend_label = ', '.join(label_parts)

        # Panel a: Transmitivity vs I_in_max
        ax_trans.plot(I_in_max_array, transmitivity_array, 'o-',
                     color=color, linewidth=2.5, markersize=8, label=legend_label, alpha=0.8)

        # Panel b: Transmitivity vs I_T_max
        ax_jmax.plot(J_max_array, transmitivity_array, 'o-',
                    color=color, linewidth=2.5, markersize=8, label=legend_label, alpha=0.8)

    # Configure panel a
    ax_trans.set_xlabel(r'$I_{\mathrm{in,max}}$', fontsize=13)
    ax_trans.set_ylabel(r'Transmitivity ($I_{\mathrm{T,max}}/I_{\mathrm{in,max}}$)', fontsize=13)
    ax_trans.set_title(r'(a) Transmitivity vs Input Current', fontsize=14)
    ax_trans.legend(fontsize=10)
    ax_trans.grid(True, alpha=0.3)

    # Configure panel b
    ax_jmax.set_xlabel(r'$I_{\mathrm{T,max}}$', fontsize=13)
    ax_jmax.set_ylabel(r'Transmitivity ($I_{\mathrm{T,max}}/I_{\mathrm{in,max}}$)', fontsize=13)
    ax_jmax.set_title(r'(b) Transmitivity vs Transmitted Current', fontsize=14)
    ax_jmax.legend(fontsize=10)
    ax_jmax.grid(True, alpha=0.3)

    fig_trans.tight_layout()

    # Set up save directory if needed
    if save_plot:
        if save_dir is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
            save_dir = os.path.join(project_root, 'Figures')
        os.makedirs(save_dir, exist_ok=True)

    if save_plot:
        # Format job indices for filename
        jobs_str = '_'.join(map(str, directory_job_indices))
        save_path = os.path.join(save_dir, f'transmitivity_analysis_{timestamp}_jobs{jobs_str}.png')
        extended_savefig(fig_trans, save_path, timestamp)

    # Create pulse traces plot if requested (one plot per directory job index)
    if plot_pulses is not False and plot_pulses is not None:
        for dir_idx, data in enumerate(loaded_data_list):
            dir_job_idx = directory_job_indices[dir_idx]

            # Extract time series data
            gap_evolution = data['gap_evolution']
            current_evolution = data['current_evolution']
            vector_potential_evolution = data['vector_potential_evolution']
            incoming_current_pulses = data['incoming_current_pulses']
            times = data['times']

            # Determine which jobs to plot
            if isinstance(plot_pulses, list):
                plot_job_indices = plot_pulses
            elif plot_pulses is True:
                plot_job_indices = range(len(gap_evolution))
            else:
                plot_job_indices = range(len(gap_evolution))

            # Create 2x2 plot
            fig_pulses, axes = plt.subplots(2, 2, figsize=(14, 10))
            ax_gap, ax_vpot = axes[0]
            ax_current, ax_input = axes[1]

            # Color cycle for different jobs
            colors_jobs = plt.cm.tab10(np.linspace(0, 1, len(plot_job_indices)))

            for idx, job_idx in enumerate(plot_job_indices):
                color = colors_jobs[idx]
                label = f'Job {job_idx}'

                # Extract data for this job
                times_job = times[job_idx]
                gaps_job = np.abs(gap_evolution[job_idx])
                current_job = current_evolution[job_idx]
                vpot_job = vector_potential_evolution[job_idx]
                input_job = incoming_current_pulses[job_idx]

                # Plot gap vs time
                ax_gap.plot(times_job, gaps_job, '-', color=color, linewidth=2, label=label, alpha=0.8)

                # Plot vector potential vs time
                ax_vpot.plot(times_job, vpot_job, '-', color=color, linewidth=2, label=label, alpha=0.8)

                # Plot current vs time
                ax_current.plot(times_job, current_job, '-', color=color, linewidth=2, label=label, alpha=0.8)

                # Plot incoming current vs time
                ax_input.plot(times_job, input_job, '-', color=color, linewidth=2, label=label, alpha=0.8)

            # Configure gap plot
            ax_gap.set_xlabel(r'Time', fontsize=12)
            ax_gap.set_ylabel(r'$|\Delta(t)|$', fontsize=12)
            ax_gap.set_title(r'(a) Gap Evolution', fontsize=13)
            ax_gap.legend(fontsize=9)
            ax_gap.grid(True, alpha=0.3)

            # Configure vector potential plot
            ax_vpot.set_xlabel(r'Time', fontsize=12)
            ax_vpot.set_ylabel(r'$A(t)$', fontsize=12)
            ax_vpot.set_title(r'(b) Vector Potential', fontsize=13)
            ax_vpot.legend(fontsize=9)
            ax_vpot.grid(True, alpha=0.3)

            # Configure current plot
            ax_current.set_xlabel(r'Time', fontsize=12)
            ax_current.set_ylabel(r'$I_{\mathrm{T}}(t)$', fontsize=12)
            ax_current.set_title(r'(c) Transmitted Current', fontsize=13)
            ax_current.legend(fontsize=9)
            ax_current.grid(True, alpha=0.3)

            # Configure incoming current plot
            ax_input.set_xlabel(r'Time', fontsize=12)
            ax_input.set_ylabel(r'$I_{\mathrm{in}}(t)$', fontsize=12)
            ax_input.set_title(r'(d) Incoming Current Pulse', fontsize=13)
            ax_input.legend(fontsize=9)
            ax_input.grid(True, alpha=0.3)

            # Add overall title if multiple directory jobs
            if len(directory_job_indices) > 1:
                fig_pulses.suptitle(f'Directory Job {dir_job_idx}', fontsize=15, y=0.995)

            fig_pulses.tight_layout()

            if save_plot:
                # Format plotted job indices for filename
                pulse_jobs_str = '_'.join(map(str, plot_job_indices))
                save_path = os.path.join(save_dir, f'pulse_traces_{timestamp}_pulses_{pulse_jobs_str}_dirjob{dir_job_idx}.png')
                extended_savefig(fig_pulses, save_path, timestamp)

    plt.show()

    # Return single dict if single index, list if multiple
    if len(loaded_data_list) == 1:
        return loaded_data_list[0]
    else:
        return loaded_data_list
