
from dataclasses import dataclass
import jax.numpy as jnp
from jax import tree_util
import jax
# describes the evolution on the system state which we want to do
# system state is described by two variables g^r and f which are defined using a correct grid of frequencies

# temperature only comes from the inital state of the system in f, so temperature can be stored in system state somehow, generated by eilenberger
@tree_util.register_pytree_node_class
class SupercondctingState:

    def __init__(self, f0, gr0 = None):
        self.gr = gr0
        self.occupation = jax.lax.stop_gradient(f0)

    @jax.jit
    def _r2a(self): 
        return -(self.gr)._involution() 

    @jax.jit
    def _f2gk(self): return self.gr @ self.occupation - self.occupation @ self._r2a()

    def __str__(self):
        return f"SupercondctingState: \n Occupation(f): {self.occupation} \n Retarded Green's function(gr): {self.gr})"

    def __del__(self):
        del self.gr
        del self.occupation

    def tree_flatten(self):
        children = self.occupation, self.gr
        aux_data = None
        return children, aux_data

    def tree_unflatten(aux_data, children):
        f, gr = children
        return SupercondctingState(f,gr)
