import jax
import jax.numpy as jnp

import nambu_support

"""A module generating the dictinoary containing all the system parameters and the relevant equilibirum occupations 
"""


def get_system_parameters(temperature: float,mesh_dictionary: dict,critical_temperature = 1.0, self_energy_coefficients = {},gap_symmetry = 's',vector_potential_params = None)->dict:
    """A function generating the dictionary containing all the system parameters

    Args:
        temperature (float): Temperature of the system we wish to study
        mesh_dictionary (dict): dictionary generated by the get_computation_grid function
        critical_temperature (float, optional): Critical temperature. Defaults to 1.
        self_energy_coefficients (dict, optional): Dictionary containing the self energy coefficients. Defaults to {}.
        gap_symmetry (str, optional): Type of gap symmetry. Defaults to 's'.
        vector_potential_params (_type_, optional): Vector potential parameters. Defaults to None.

    Returns:
        dict: Dictionary containing all the system parameters. Temperature, critical temperature, vector potential, gap symmetry, and self energy coefficients
    """
    
    param_dict = {}

    param_dict['temperature'] = temperature
    param_dict['critical_temperature'] = critical_temperature
 
    param_dict['vector_potential'] = get_vector_potential(vector_potential_params = vector_potential_params)   
    param_dict['gap_symmetry'] = generate_gap_symmetry_function(gap_symmetry = gap_symmetry, theta_grid= mesh_dictionary['nambu_theta_grid'])
    param_dict['bcs_coupling'] = get_BCS_coupling(cutoff = mesh_dictionary['cutoff'],critical_temperature = critical_temperature)

    param_dict['self_energy_coefficients'] = self_energy_coefficients

    return param_dict

def generate_gap_symmetry_function(gap_symmetry: str,theta_grid: jnp.ndarray) -> jnp.ndarray:
    """A function generating the gap symmetry function given the symmetry type

    Args:
        gap_symmetry (str): description of the gap symmetry function: s, d-nodal or d-antinodal
        theta_grid (jnp.array): angle meshgrid generated by the get_computation_grid function

    Raises:
        ValueError: If the gap symmetry is not s, d-nodal or d-antinodal

    Returns:
        jnp.ndarray: The gap symmetry function defined over the angle meshgrid
    """
    if gap_symmetry == 's':
        return jnp.ones_like(theta_grid)
    elif gap_symmetry == 'd-nodal':
        return jnp.sqrt(2.)*jnp.sin(2.*theta_grid)
    elif gap_symmetry == 'd-antinodal':
        return jnp.sqrt(2.)*jnp.cos(2.*theta_grid)
    else:
        raise ValueError("Invalid gap symmetry")


def get_BCS_coupling(cutoff: float,critical_temperature: float)->float:
    """A function returning the bcs coupling given the critical temperature

    Args:
        cutoff (float): high energy cutoff of the theory
        critical_temperature (float): critical temperature in the system

    Returns:
        float: Bcs coupling constant lambda
    """
    ### This is a useful function which gives the relation between BCS lambda and Tc for a fixed cutoff in the case of clean s-wave BCS equation 
    return 1./jnp.log(nambu_support.get_bcs_gap_constant()*cutoff/critical_temperature) 

def get_vector_potential(vector_potential_params = None) -> float:
    """A function returning the vector potential

    Args:
        vector_potential_params (vector_potential_params, optional): Vector potential parameters. Defaults to None.

    Returns:
        float: Vector potential value at time t
    """
    #TODO:has to be generalized, since function should not be passed to jax jitted function
    #TODO: in general, given timestamps it should return the vector potential
    return 0

def get_initial_occupation_numbers(nambu_identity: jnp.ndarray, omega_grid: jnp.ndarray, temperature: float) -> jnp.ndarray:
    """A function returning the initial occupation numbers given temperature T. f function

    Args:
        nambu_identity (jnp.ndarray): Identity matrix in nambu space 
        omega_grid (jnp.ndarray): Grid of frequencies
        temperature (jnp.ndarray): System temperature

    Returns:
        jnp.ndarray: f distribution function defined on the meshgrid within nambu space
    """
    return nambu_identity*jnp.tanh(0.5*omega_grid/temperature)
